// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_session_recovery.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const discardAgentSession = `-- name: DiscardAgentSession :execresult
UPDATE agent_sessions
SET discarded_at = ?, discarded_by = ?, discarded_decision_id = ?, discard_reason = ?
WHERE id = ? AND project_id = ? AND discarded_at IS NULL
`

type DiscardAgentSessionParams struct {
	DiscardedAt         sql.NullString
	DiscardedBy         sql.NullInt64
	DiscardedDecisionID sql.NullInt64
	DiscardReason       string
	ID                  int64
	ProjectID           sql.NullInt64
}

func (q *Queries) DiscardAgentSession(ctx context.Context, arg DiscardAgentSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, discardAgentSession,
		arg.DiscardedAt,
		arg.DiscardedBy,
		arg.DiscardedDecisionID,
		arg.DiscardReason,
		arg.ID,
		arg.ProjectID,
	)
}

const getAgentSessionRecovery = `-- name: GetAgentSessionRecovery :one
SELECT id, project_id, pid, started_at, discarded_at, discarded_by,
       discarded_decision_id, discard_reason
FROM agent_sessions
WHERE id = ?
`

type GetAgentSessionRecoveryRow struct {
	ID                  int64
	ProjectID           sql.NullInt64
	Pid                 int64
	StartedAt           string
	DiscardedAt         sql.NullString
	DiscardedBy         sql.NullInt64
	DiscardedDecisionID sql.NullInt64
	DiscardReason       string
}

func (q *Queries) GetAgentSessionRecovery(ctx context.Context, id int64) (GetAgentSessionRecoveryRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionRecovery, id)
	var i GetAgentSessionRecoveryRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Pid,
		&i.StartedAt,
		&i.DiscardedAt,
		&i.DiscardedBy,
		&i.DiscardedDecisionID,
		&i.DiscardReason,
	)
	return i, err
}
