// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decision.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const answerDecision = `-- name: AnswerDecision :execresult
UPDATE decisions
SET status = 'answered', answer_label = ?, answer_text = ?, answered_at = ?
WHERE id = ? AND status = 'open'
`

type AnswerDecisionParams struct {
	AnswerLabel string
	AnswerText  string
	AnsweredAt  sql.NullString
	ID          int64
}

func (q *Queries) AnswerDecision(ctx context.Context, arg AnswerDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, answerDecision,
		arg.AnswerLabel,
		arg.AnswerText,
		arg.AnsweredAt,
		arg.ID,
	)
}

const applyDecisionDefault = `-- name: ApplyDecisionDefault :execresult
UPDATE decisions
SET status = 'answered', answer_label = ?, answered_at = ?, default_applied_at = ?
WHERE id = ? AND status = 'open'
`

type ApplyDecisionDefaultParams struct {
	AnswerLabel      string
	AnsweredAt       sql.NullString
	DefaultAppliedAt sql.NullString
	ID               int64
}

func (q *Queries) ApplyDecisionDefault(ctx context.Context, arg ApplyDecisionDefaultParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, applyDecisionDefault,
		arg.AnswerLabel,
		arg.AnsweredAt,
		arg.DefaultAppliedAt,
		arg.ID,
	)
}

const countAppliedDecisions = `-- name: CountAppliedDecisions :one
SELECT COUNT(*)
FROM decisions
WHERE goal_id = ? AND status = 'applied'
`

func (q *Queries) CountAppliedDecisions(ctx context.Context, goalID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppliedDecisions, goalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppliedDecisionsForTask = `-- name: CountAppliedDecisionsForTask :one
SELECT COUNT(*)
FROM decisions
WHERE goal_id = ? AND task_id = ? AND status = 'applied'
`

type CountAppliedDecisionsForTaskParams struct {
	GoalID int64
	TaskID sql.NullInt64
}

func (q *Queries) CountAppliedDecisionsForTask(ctx context.Context, arg CountAppliedDecisionsForTaskParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAppliedDecisionsForTask, arg.GoalID, arg.TaskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDecision = `-- name: CreateDecision :one
INSERT INTO decisions (
  goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, agent_session_id, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateDecisionParams struct {
	GoalID         int64
	TaskID         sql.NullInt64
	Kind           string
	Question       string
	Options        string
	Status         string
	DefaultOption  string
	DefaultAfterMs sql.NullInt64
	AgentSessionID int64
	CreatedAt      string
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDecision,
		arg.GoalID,
		arg.TaskID,
		arg.Kind,
		arg.Question,
		arg.Options,
		arg.Status,
		arg.DefaultOption,
		arg.DefaultAfterMs,
		arg.AgentSessionID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDecision = `-- name: GetDecision :one
SELECT
  id, goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE id = ?
`

type GetDecisionRow struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) GetDecision(ctx context.Context, id int64) (GetDecisionRow, error) {
	row := q.db.QueryRowContext(ctx, getDecision, id)
	var i GetDecisionRow
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.TaskID,
		&i.Kind,
		&i.Question,
		&i.Options,
		&i.Status,
		&i.DefaultOption,
		&i.DefaultAfterMs,
		&i.DefaultAppliedAt,
		&i.AnswerLabel,
		&i.AnswerText,
		&i.AnsweredAt,
		&i.AppliedAt,
		&i.AgentSessionID,
		&i.CreatedAt,
	)
	return i, err
}

const listAllOpenDecisions = `-- name: ListAllOpenDecisions :many
SELECT
  id, goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE status = 'open'
ORDER BY created_at
`

type ListAllOpenDecisionsRow struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) ListAllOpenDecisions(ctx context.Context) ([]ListAllOpenDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllOpenDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllOpenDecisionsRow
	for rows.Next() {
		var i ListAllOpenDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.Question,
			&i.Options,
			&i.Status,
			&i.DefaultOption,
			&i.DefaultAfterMs,
			&i.DefaultAppliedAt,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.AppliedAt,
			&i.AgentSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnsweredDecisionForID = `-- name: ListAnsweredDecisionForID :many
SELECT
  id, goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE status = 'answered' AND id = ?
ORDER BY answered_at
`

type ListAnsweredDecisionForIDRow struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) ListAnsweredDecisionForID(ctx context.Context, id int64) ([]ListAnsweredDecisionForIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnsweredDecisionForID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnsweredDecisionForIDRow
	for rows.Next() {
		var i ListAnsweredDecisionForIDRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.Question,
			&i.Options,
			&i.Status,
			&i.DefaultOption,
			&i.DefaultAfterMs,
			&i.DefaultAppliedAt,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.AppliedAt,
			&i.AgentSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnsweredDecisionsForAgentSession = `-- name: ListAnsweredDecisionsForAgentSession :many
SELECT
  id, goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE status = 'answered' AND agent_session_id = ?
ORDER BY answered_at
`

type ListAnsweredDecisionsForAgentSessionRow struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) ListAnsweredDecisionsForAgentSession(ctx context.Context, agentSessionID int64) ([]ListAnsweredDecisionsForAgentSessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnsweredDecisionsForAgentSession, agentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnsweredDecisionsForAgentSessionRow
	for rows.Next() {
		var i ListAnsweredDecisionsForAgentSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.Question,
			&i.Options,
			&i.Status,
			&i.DefaultOption,
			&i.DefaultAfterMs,
			&i.DefaultAppliedAt,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.AppliedAt,
			&i.AgentSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppliedDecisions = `-- name: ListAppliedDecisions :many
SELECT
  id, goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE goal_id = ? AND status = 'applied'
ORDER BY answered_at DESC, applied_at DESC, id DESC
LIMIT ?2
`

type ListAppliedDecisionsParams struct {
	GoalID       int64
	HistoryLimit int64
}

type ListAppliedDecisionsRow struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) ListAppliedDecisions(ctx context.Context, arg ListAppliedDecisionsParams) ([]ListAppliedDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppliedDecisions, arg.GoalID, arg.HistoryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppliedDecisionsRow
	for rows.Next() {
		var i ListAppliedDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.Question,
			&i.Options,
			&i.Status,
			&i.DefaultOption,
			&i.DefaultAfterMs,
			&i.DefaultAppliedAt,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.AppliedAt,
			&i.AgentSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppliedDecisionsForTask = `-- name: ListAppliedDecisionsForTask :many
SELECT
  id, goal_id, COALESCE(task_id, '') AS task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE goal_id = ? AND task_id = ? AND status = 'applied'
ORDER BY answered_at DESC, applied_at DESC, id DESC
LIMIT ?3
`

type ListAppliedDecisionsForTaskParams struct {
	GoalID       int64
	TaskID       sql.NullInt64
	HistoryLimit int64
}

type ListAppliedDecisionsForTaskRow struct {
	ID               int64
	GoalID           int64
	TaskID           int64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) ListAppliedDecisionsForTask(ctx context.Context, arg ListAppliedDecisionsForTaskParams) ([]ListAppliedDecisionsForTaskRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppliedDecisionsForTask, arg.GoalID, arg.TaskID, arg.HistoryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppliedDecisionsForTaskRow
	for rows.Next() {
		var i ListAppliedDecisionsForTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.Question,
			&i.Options,
			&i.Status,
			&i.DefaultOption,
			&i.DefaultAfterMs,
			&i.DefaultAppliedAt,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.AppliedAt,
			&i.AgentSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredDecisions = `-- name: ListExpiredDecisions :many
SELECT
  id, goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE status = 'open' AND default_after_ms IS NOT NULL AND default_option != ''
ORDER BY created_at
`

type ListExpiredDecisionsRow struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) ListExpiredDecisions(ctx context.Context) ([]ListExpiredDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredDecisionsRow
	for rows.Next() {
		var i ListExpiredDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.Question,
			&i.Options,
			&i.Status,
			&i.DefaultOption,
			&i.DefaultAfterMs,
			&i.DefaultAppliedAt,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.AppliedAt,
			&i.AgentSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenDecisions = `-- name: ListOpenDecisions :many
SELECT
  id, goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE goal_id = ? AND status = 'open'
ORDER BY created_at
`

type ListOpenDecisionsRow struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) ListOpenDecisions(ctx context.Context, goalID int64) ([]ListOpenDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenDecisions, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenDecisionsRow
	for rows.Next() {
		var i ListOpenDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.Question,
			&i.Options,
			&i.Status,
			&i.DefaultOption,
			&i.DefaultAfterMs,
			&i.DefaultAppliedAt,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.AppliedAt,
			&i.AgentSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnappliedDecisions = `-- name: ListUnappliedDecisions :many
SELECT
  id, goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE status = 'answered'
ORDER BY answered_at
`

type ListUnappliedDecisionsRow struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) ListUnappliedDecisions(ctx context.Context) ([]ListUnappliedDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnappliedDecisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnappliedDecisionsRow
	for rows.Next() {
		var i ListUnappliedDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.Question,
			&i.Options,
			&i.Status,
			&i.DefaultOption,
			&i.DefaultAfterMs,
			&i.DefaultAppliedAt,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.AppliedAt,
			&i.AgentSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnappliedDecisionsForGoal = `-- name: ListUnappliedDecisionsForGoal :many
SELECT
  id, goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE status = 'answered'
  AND goal_id = ?
ORDER BY answered_at
`

type ListUnappliedDecisionsForGoalRow struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) ListUnappliedDecisionsForGoal(ctx context.Context, goalID int64) ([]ListUnappliedDecisionsForGoalRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnappliedDecisionsForGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnappliedDecisionsForGoalRow
	for rows.Next() {
		var i ListUnappliedDecisionsForGoalRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.Question,
			&i.Options,
			&i.Status,
			&i.DefaultOption,
			&i.DefaultAfterMs,
			&i.DefaultAppliedAt,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.AppliedAt,
			&i.AgentSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnappliedDecisionsForProject = `-- name: ListUnappliedDecisionsForProject :many
SELECT
  id, goal_id, task_id, kind, question, options, status,
  default_option, default_after_ms, default_applied_at,
  answer_label, answer_text, answered_at, applied_at, agent_session_id, created_at
FROM decisions
WHERE status = 'answered'
  AND goal_id IN (SELECT id FROM goals WHERE project_id = ?)
ORDER BY answered_at
`

type ListUnappliedDecisionsForProjectRow struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

func (q *Queries) ListUnappliedDecisionsForProject(ctx context.Context, projectID int64) ([]ListUnappliedDecisionsForProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnappliedDecisionsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnappliedDecisionsForProjectRow
	for rows.Next() {
		var i ListUnappliedDecisionsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.Question,
			&i.Options,
			&i.Status,
			&i.DefaultOption,
			&i.DefaultAfterMs,
			&i.DefaultAppliedAt,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.AppliedAt,
			&i.AgentSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDecisionApplied = `-- name: MarkDecisionApplied :exec
UPDATE decisions
SET status = 'applied', applied_at = ?
WHERE id = ? AND status = 'answered'
`

type MarkDecisionAppliedParams struct {
	AppliedAt sql.NullString
	ID        int64
}

func (q *Queries) MarkDecisionApplied(ctx context.Context, arg MarkDecisionAppliedParams) error {
	_, err := q.db.ExecContext(ctx, markDecisionApplied, arg.AppliedAt, arg.ID)
	return err
}

const resolveDecisionIDByLegacyPrefix = `-- name: ResolveDecisionIDByLegacyPrefix :many
SELECT id FROM decisions
WHERE legacy_id >= ?1 AND legacy_id < ?2
LIMIT 2
`

type ResolveDecisionIDByLegacyPrefixParams struct {
	Prefix    sql.NullString
	PrefixEnd sql.NullString
}

func (q *Queries) ResolveDecisionIDByLegacyPrefix(ctx context.Context, arg ResolveDecisionIDByLegacyPrefixParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, resolveDecisionIDByLegacyPrefix, arg.Prefix, arg.PrefixEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const withdrawDecision = `-- name: WithdrawDecision :execresult
UPDATE decisions
SET status = 'withdrawn', answer_text = ?
WHERE id = ? AND status = 'open'
`

type WithdrawDecisionParams struct {
	AnswerText string
	ID         int64
}

func (q *Queries) WithdrawDecision(ctx context.Context, arg WithdrawDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, withdrawDecision, arg.AnswerText, arg.ID)
}
