// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const applyCompletionDecision = `-- name: ApplyCompletionDecision :execresult
UPDATE decisions SET status = 'applied', answer_label = 'approve',
  answered_at = ?, applied_at = ?
WHERE id = ?
`

type ApplyCompletionDecisionParams struct {
	AnsweredAt sql.NullString
	AppliedAt  sql.NullString
	ID         int64
}

func (q *Queries) ApplyCompletionDecision(ctx context.Context, arg ApplyCompletionDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, applyCompletionDecision, arg.AnsweredAt, arg.AppliedAt, arg.ID)
}

const applyGoalApprovalDecision = `-- name: ApplyGoalApprovalDecision :execresult
UPDATE decisions SET status = 'applied', answer_label = 'approve',
  answered_at = ?, applied_at = ?
WHERE id = ? AND kind = 'goal_approval' AND status = 'open'
`

type ApplyGoalApprovalDecisionParams struct {
	AnsweredAt sql.NullString
	AppliedAt  sql.NullString
	ID         int64
}

func (q *Queries) ApplyGoalApprovalDecision(ctx context.Context, arg ApplyGoalApprovalDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, applyGoalApprovalDecision, arg.AnsweredAt, arg.AppliedAt, arg.ID)
}

const countOpenDecisionsForGoal = `-- name: CountOpenDecisionsForGoal :one
SELECT COUNT(*)
FROM decisions
WHERE goal_id = ? AND status = 'open'
`

func (q *Queries) CountOpenDecisionsForGoal(ctx context.Context, goalID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenDecisionsForGoal, goalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (
  project_id, derived_from_goal_id, content, status, creator,
  result_summary,
  work_done, now_possible, how_to_verify, surprises, needs_review, next_steps,
  created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, '', '', '', '', '', '', '', ?, ?)
RETURNING id
`

type CreateGoalParams struct {
	ProjectID         int64
	DerivedFromGoalID sql.NullInt64
	Content           string
	Status            string
	Creator           string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.ProjectID,
		arg.DerivedFromGoalID,
		arg.Content,
		arg.Status,
		arg.Creator,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCompletionDecisionGoalID = `-- name: GetCompletionDecisionGoalID :one
SELECT goal_id
FROM decisions
WHERE id = ? AND kind = 'completion' AND status = 'open'
`

func (q *Queries) GetCompletionDecisionGoalID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCompletionDecisionGoalID, id)
	var goal_id int64
	err := row.Scan(&goal_id)
	return goal_id, err
}

const getGoal = `-- name: GetGoal :one
SELECT
	  id, project_id, NULLIF(CAST(derived_from_goal_id AS INTEGER), 0) AS derived_from_goal_id, content, status, creator, result_summary,
	  work_done, now_possible, how_to_verify, surprises, needs_review, next_steps,
  created_at, updated_at
FROM goals
WHERE id = ?
`

type GetGoalRow struct {
	ID                int64
	ProjectID         int64
	DerivedFromGoalID sql.NullInt64
	Content           string
	Status            string
	Creator           string
	ResultSummary     string
	WorkDone          string
	NowPossible       string
	HowToVerify       string
	Surprises         string
	NeedsReview       string
	NextSteps         string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) GetGoal(ctx context.Context, id int64) (GetGoalRow, error) {
	row := q.db.QueryRowContext(ctx, getGoal, id)
	var i GetGoalRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DerivedFromGoalID,
		&i.Content,
		&i.Status,
		&i.Creator,
		&i.ResultSummary,
		&i.WorkDone,
		&i.NowPossible,
		&i.HowToVerify,
		&i.Surprises,
		&i.NeedsReview,
		&i.NextSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoalApprovalDecisionGoalID = `-- name: GetGoalApprovalDecisionGoalID :one
SELECT goal_id
FROM decisions
WHERE id = ? AND kind = 'goal_approval' AND status = 'open'
`

func (q *Queries) GetGoalApprovalDecisionGoalID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGoalApprovalDecisionGoalID, id)
	var goal_id int64
	err := row.Scan(&goal_id)
	return goal_id, err
}

const listAllGoals = `-- name: ListAllGoals :many
SELECT
  id, project_id, derived_from_goal_id, content, status, creator, result_summary,
  work_done, now_possible, how_to_verify, surprises, needs_review, next_steps,
  created_at, updated_at
FROM goals
ORDER BY created_at
`

type ListAllGoalsRow struct {
	ID                int64
	ProjectID         int64
	DerivedFromGoalID sql.NullInt64
	Content           string
	Status            string
	Creator           string
	ResultSummary     string
	WorkDone          string
	NowPossible       string
	HowToVerify       string
	Surprises         string
	NeedsReview       string
	NextSteps         string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) ListAllGoals(ctx context.Context) ([]ListAllGoalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllGoalsRow
	for rows.Next() {
		var i ListAllGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DerivedFromGoalID,
			&i.Content,
			&i.Status,
			&i.Creator,
			&i.ResultSummary,
			&i.WorkDone,
			&i.NowPossible,
			&i.HowToVerify,
			&i.Surprises,
			&i.NeedsReview,
			&i.NextSteps,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDerivedGoals = `-- name: ListDerivedGoals :many
SELECT
  id, project_id, derived_from_goal_id, content, status, creator, result_summary,
  work_done, now_possible, how_to_verify, surprises, needs_review, next_steps,
  created_at, updated_at
FROM goals
WHERE derived_from_goal_id = ?
ORDER BY created_at
`

type ListDerivedGoalsRow struct {
	ID                int64
	ProjectID         int64
	DerivedFromGoalID sql.NullInt64
	Content           string
	Status            string
	Creator           string
	ResultSummary     string
	WorkDone          string
	NowPossible       string
	HowToVerify       string
	Surprises         string
	NeedsReview       string
	NextSteps         string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) ListDerivedGoals(ctx context.Context, derivedFromGoalID sql.NullInt64) ([]ListDerivedGoalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDerivedGoals, derivedFromGoalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDerivedGoalsRow
	for rows.Next() {
		var i ListDerivedGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DerivedFromGoalID,
			&i.Content,
			&i.Status,
			&i.Creator,
			&i.ResultSummary,
			&i.WorkDone,
			&i.NowPossible,
			&i.HowToVerify,
			&i.Surprises,
			&i.NeedsReview,
			&i.NextSteps,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT
  id, project_id, derived_from_goal_id, content, status, creator, result_summary,
  work_done, now_possible, how_to_verify, surprises, needs_review, next_steps,
  created_at, updated_at
FROM goals
WHERE project_id = ?
ORDER BY created_at
`

type ListGoalsRow struct {
	ID                int64
	ProjectID         int64
	DerivedFromGoalID sql.NullInt64
	Content           string
	Status            string
	Creator           string
	ResultSummary     string
	WorkDone          string
	NowPossible       string
	HowToVerify       string
	Surprises         string
	NeedsReview       string
	NextSteps         string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) ListGoals(ctx context.Context, projectID int64) ([]ListGoalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoals, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalsRow
	for rows.Next() {
		var i ListGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DerivedFromGoalID,
			&i.Content,
			&i.Status,
			&i.Creator,
			&i.ResultSummary,
			&i.WorkDone,
			&i.NowPossible,
			&i.HowToVerify,
			&i.Surprises,
			&i.NeedsReview,
			&i.NextSteps,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGoalActive = `-- name: MarkGoalActive :execresult
UPDATE goals SET status = 'active', updated_at = ?
WHERE id = ? AND status = 'proposed'
`

type MarkGoalActiveParams struct {
	UpdatedAt string
	ID        int64
}

func (q *Queries) MarkGoalActive(ctx context.Context, arg MarkGoalActiveParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markGoalActive, arg.UpdatedAt, arg.ID)
}

const markGoalDone = `-- name: MarkGoalDone :execresult
UPDATE goals SET status = 'done', updated_at = ?
WHERE id = ?
`

type MarkGoalDoneParams struct {
	UpdatedAt string
	ID        int64
}

func (q *Queries) MarkGoalDone(ctx context.Context, arg MarkGoalDoneParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markGoalDone, arg.UpdatedAt, arg.ID)
}

const markGoalDropped = `-- name: MarkGoalDropped :execresult
UPDATE goals SET status = 'dropped', updated_at = ?
WHERE id = ? AND status = 'proposed'
`

type MarkGoalDroppedParams struct {
	UpdatedAt string
	ID        int64
}

func (q *Queries) MarkGoalDropped(ctx context.Context, arg MarkGoalDroppedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markGoalDropped, arg.UpdatedAt, arg.ID)
}

const rejectGoalApprovalDecision = `-- name: RejectGoalApprovalDecision :execresult
UPDATE decisions SET status = 'answered', answer_label = 'reject',
  answer_text = ?, answered_at = ?
WHERE id = ? AND kind = 'goal_approval' AND status = 'open'
`

type RejectGoalApprovalDecisionParams struct {
	AnswerText string
	AnsweredAt sql.NullString
	ID         int64
}

func (q *Queries) RejectGoalApprovalDecision(ctx context.Context, arg RejectGoalApprovalDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, rejectGoalApprovalDecision, arg.AnswerText, arg.AnsweredAt, arg.ID)
}

const resolveGoalIDByLegacyPrefix = `-- name: ResolveGoalIDByLegacyPrefix :many
SELECT id FROM goals
WHERE legacy_id >= ?1 AND legacy_id < ?2
LIMIT 2
`

type ResolveGoalIDByLegacyPrefixParams struct {
	Prefix    sql.NullString
	PrefixEnd sql.NullString
}

func (q *Queries) ResolveGoalIDByLegacyPrefix(ctx context.Context, arg ResolveGoalIDByLegacyPrefixParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, resolveGoalIDByLegacyPrefix, arg.Prefix, arg.PrefixEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGoalDerivedFrom = `-- name: SetGoalDerivedFrom :execresult
UPDATE goals SET derived_from_goal_id = ?, updated_at = ?
WHERE id = ?
`

type SetGoalDerivedFromParams struct {
	DerivedFromGoalID sql.NullInt64
	UpdatedAt         string
	ID                int64
}

func (q *Queries) SetGoalDerivedFrom(ctx context.Context, arg SetGoalDerivedFromParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setGoalDerivedFrom, arg.DerivedFromGoalID, arg.UpdatedAt, arg.ID)
}

const updateGoalCompletionReport = `-- name: UpdateGoalCompletionReport :execresult
UPDATE goals SET
  result_summary = ?,
  work_done = ?, now_possible = ?, how_to_verify = ?,
  surprises = ?, needs_review = ?, next_steps = ?, updated_at = ?
WHERE id = ?
`

type UpdateGoalCompletionReportParams struct {
	ResultSummary string
	WorkDone      string
	NowPossible   string
	HowToVerify   string
	Surprises     string
	NeedsReview   string
	NextSteps     string
	UpdatedAt     string
	ID            int64
}

func (q *Queries) UpdateGoalCompletionReport(ctx context.Context, arg UpdateGoalCompletionReportParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateGoalCompletionReport,
		arg.ResultSummary,
		arg.WorkDone,
		arg.NowPossible,
		arg.HowToVerify,
		arg.Surprises,
		arg.NeedsReview,
		arg.NextSteps,
		arg.UpdatedAt,
		arg.ID,
	)
}

const updateGoalContent = `-- name: UpdateGoalContent :execresult
UPDATE goals SET content = ?, updated_at = ?
WHERE id = ? AND status = 'proposed'
`

type UpdateGoalContentParams struct {
	Content   string
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdateGoalContent(ctx context.Context, arg UpdateGoalContentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateGoalContent, arg.Content, arg.UpdatedAt, arg.ID)
}

const withdrawActiveGoal = `-- name: WithdrawActiveGoal :execresult
UPDATE goals SET status = 'dropped', result_summary = ?, updated_at = ?
WHERE id = ? AND status = 'active'
`

type WithdrawActiveGoalParams struct {
	ResultSummary string
	UpdatedAt     string
	ID            int64
}

func (q *Queries) WithdrawActiveGoal(ctx context.Context, arg WithdrawActiveGoalParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, withdrawActiveGoal, arg.ResultSummary, arg.UpdatedAt, arg.ID)
}
