// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal_handoff.sql

package sqlcgen

import (
	"context"
)

const listOpenGoalHandoffs = `-- name: ListOpenGoalHandoffs :many
SELECT id, goal_id, requested_by, received_by,
       requested_at, received_at, completed_report_at,
       request_report, complete_report
FROM goal_handoffs
WHERE completed_report_at IS NULL
ORDER BY id
`

func (q *Queries) ListOpenGoalHandoffs(ctx context.Context) ([]GoalHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listOpenGoalHandoffs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalHandoff
	for rows.Next() {
		var i GoalHandoff
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.RequestedBy,
			&i.ReceivedBy,
			&i.RequestedAt,
			&i.ReceivedAt,
			&i.CompletedReportAt,
			&i.RequestReport,
			&i.CompleteReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
