// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goal.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const applyGoalApprovalDecision = `-- name: ApplyGoalApprovalDecision :execresult
UPDATE decisions SET status = 'applied', answer_label = 'approve',
  answered_at = ?, applied_at = ?
WHERE id = ? AND kind = 'goal_approval' AND status = 'open'
`

type ApplyGoalApprovalDecisionParams struct {
	AnsweredAt sql.NullString
	AppliedAt  sql.NullString
	ID         int64
}

func (q *Queries) ApplyGoalApprovalDecision(ctx context.Context, arg ApplyGoalApprovalDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, applyGoalApprovalDecision, arg.AnsweredAt, arg.AppliedAt, arg.ID)
}

const approveGoalReviewDecision = `-- name: ApproveGoalReviewDecision :execresult
UPDATE decisions
SET status = 'applied', answer_label = 'approve', answered_at = ?, applied_at = ?
WHERE id = ? AND kind = 'goal_review' AND status = 'open'
`

type ApproveGoalReviewDecisionParams struct {
	AnsweredAt sql.NullString
	AppliedAt  sql.NullString
	ID         int64
}

func (q *Queries) ApproveGoalReviewDecision(ctx context.Context, arg ApproveGoalReviewDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, approveGoalReviewDecision, arg.AnsweredAt, arg.AppliedAt, arg.ID)
}

const countApprovedGoalReviewsForGoal = `-- name: CountApprovedGoalReviewsForGoal :one
SELECT COUNT(*)
FROM decisions
WHERE goal_id = ? AND kind = 'goal_review' AND status = 'applied' AND answer_label = 'approve'
`

func (q *Queries) CountApprovedGoalReviewsForGoal(ctx context.Context, goalID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApprovedGoalReviewsForGoal, goalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenDecisionsForGoal = `-- name: CountOpenDecisionsForGoal :one
SELECT COUNT(*)
FROM decisions
WHERE goal_id = ? AND status = 'open'
`

func (q *Queries) CountOpenDecisionsForGoal(ctx context.Context, goalID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenDecisionsForGoal, goalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (
  project_id, derived_from_goal_id, content, status, creator,
  result_summary,
  work_done, now_possible, how_to_verify, surprises, needs_review,
  created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, '', '', '', '', '', '', ?, ?)
RETURNING id
`

type CreateGoalParams struct {
	ProjectID         int64
	DerivedFromGoalID sql.NullInt64
	Content           string
	Status            string
	Creator           string
	CreatedAt         string
	UpdatedAt         string
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.ProjectID,
		arg.DerivedFromGoalID,
		arg.Content,
		arg.Status,
		arg.Creator,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteNextGoals = `-- name: DeleteNextGoals :exec
DELETE FROM next_goals
WHERE goal_id = ?
`

func (q *Queries) DeleteNextGoals(ctx context.Context, goalID int64) error {
	_, err := q.db.ExecContext(ctx, deleteNextGoals, goalID)
	return err
}

const finalizeGoalReview = `-- name: FinalizeGoalReview :execresult
UPDATE goals SET status = 'done', updated_at = ?
WHERE id = ? AND status = 'active'
`

type FinalizeGoalReviewParams struct {
	UpdatedAt string
	ID        int64
}

func (q *Queries) FinalizeGoalReview(ctx context.Context, arg FinalizeGoalReviewParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, finalizeGoalReview, arg.UpdatedAt, arg.ID)
}

const getGoal = `-- name: GetGoal :one
SELECT
  id, project_id, NULLIF(CAST(derived_from_goal_id AS INTEGER), 0) AS derived_from_goal_id,
  content, spec, plan, status, creator, result_summary,
  work_done, now_possible, how_to_verify, surprises, needs_review,
  created_at, updated_at
FROM goals
WHERE id = ?
`

type GetGoalRow struct {
	ID                int64
	ProjectID         int64
	DerivedFromGoalID interface{}
	Content           string
	Spec              string
	Plan              string
	Status            string
	Creator           string
	ResultSummary     string
	WorkDone          string
	NowPossible       string
	HowToVerify       string
	Surprises         string
	NeedsReview       string
	CreatedAt         string
	UpdatedAt         string
}

// derived_from_goal_id is cast because a dangling reference can hold a value
// SQLite could not coerce to INTEGER, and the goal detail view has to render
// rather than fail. NULLIF keeps 0 meaning "no parent".
func (q *Queries) GetGoal(ctx context.Context, id int64) (GetGoalRow, error) {
	row := q.db.QueryRowContext(ctx, getGoal, id)
	var i GetGoalRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DerivedFromGoalID,
		&i.Content,
		&i.Spec,
		&i.Plan,
		&i.Status,
		&i.Creator,
		&i.ResultSummary,
		&i.WorkDone,
		&i.NowPossible,
		&i.HowToVerify,
		&i.Surprises,
		&i.NeedsReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoalApprovalDecisionGoalID = `-- name: GetGoalApprovalDecisionGoalID :one
SELECT goal_id
FROM decisions
WHERE id = ? AND kind = 'goal_approval' AND status = 'open'
`

func (q *Queries) GetGoalApprovalDecisionGoalID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGoalApprovalDecisionGoalID, id)
	var goal_id int64
	err := row.Scan(&goal_id)
	return goal_id, err
}

const getGoalProjectID = `-- name: GetGoalProjectID :one
SELECT project_id
FROM goals
WHERE id = ?
`

func (q *Queries) GetGoalProjectID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGoalProjectID, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const getGoalStatus = `-- name: GetGoalStatus :one
SELECT status
FROM goals
WHERE id = ?
`

func (q *Queries) GetGoalStatus(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getGoalStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getLatestGoalReviewID = `-- name: GetLatestGoalReviewID :one
SELECT id
FROM decisions
WHERE goal_id = ? AND kind = 'goal_review'
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestGoalReviewID(ctx context.Context, goalID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestGoalReviewID, goalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOpenGoalReviewGoalID = `-- name: GetOpenGoalReviewGoalID :one
SELECT goal_id
FROM decisions
WHERE id = ? AND kind = 'goal_review' AND status = 'open'
`

func (q *Queries) GetOpenGoalReviewGoalID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOpenGoalReviewGoalID, id)
	var goal_id int64
	err := row.Scan(&goal_id)
	return goal_id, err
}

const hasGoalReview = `-- name: HasGoalReview :one
SELECT EXISTS(
  SELECT 1 FROM decisions
  WHERE goal_id = ? AND kind = 'goal_review'
)
`

func (q *Queries) HasGoalReview(ctx context.Context, goalID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasGoalReview, goalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertGoalConfirmation = `-- name: InsertGoalConfirmation :exec
INSERT INTO goal_confirmations (goal_id, note, confirmed_at)
VALUES (?, ?, ?)
`

type InsertGoalConfirmationParams struct {
	GoalID      int64
	Note        string
	ConfirmedAt string
}

func (q *Queries) InsertGoalConfirmation(ctx context.Context, arg InsertGoalConfirmationParams) error {
	_, err := q.db.ExecContext(ctx, insertGoalConfirmation, arg.GoalID, arg.Note, arg.ConfirmedAt)
	return err
}

const insertNextGoal = `-- name: InsertNextGoal :exec
INSERT INTO next_goals (goal_id, next_goal_id, created_at)
VALUES (?, ?, ?)
`

type InsertNextGoalParams struct {
	GoalID     int64
	NextGoalID int64
	CreatedAt  string
}

func (q *Queries) InsertNextGoal(ctx context.Context, arg InsertNextGoalParams) error {
	_, err := q.db.ExecContext(ctx, insertNextGoal, arg.GoalID, arg.NextGoalID, arg.CreatedAt)
	return err
}

const listAllGoals = `-- name: ListAllGoals :many
SELECT
  id, project_id, derived_from_goal_id, content, spec, plan, status, creator, result_summary,
  work_done, now_possible, how_to_verify, surprises, needs_review,
  created_at, updated_at
FROM goals
ORDER BY created_at
`

func (q *Queries) ListAllGoals(ctx context.Context) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listAllGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DerivedFromGoalID,
			&i.Content,
			&i.Spec,
			&i.Plan,
			&i.Status,
			&i.Creator,
			&i.ResultSummary,
			&i.WorkDone,
			&i.NowPossible,
			&i.HowToVerify,
			&i.Surprises,
			&i.NeedsReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDerivedGoals = `-- name: ListDerivedGoals :many
SELECT
  id, project_id, derived_from_goal_id, content, spec, plan, status, creator, result_summary,
  work_done, now_possible, how_to_verify, surprises, needs_review,
  created_at, updated_at
FROM goals
WHERE derived_from_goal_id = ?
ORDER BY created_at
`

func (q *Queries) ListDerivedGoals(ctx context.Context, derivedFromGoalID sql.NullInt64) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listDerivedGoals, derivedFromGoalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DerivedFromGoalID,
			&i.Content,
			&i.Spec,
			&i.Plan,
			&i.Status,
			&i.Creator,
			&i.ResultSummary,
			&i.WorkDone,
			&i.NowPossible,
			&i.HowToVerify,
			&i.Surprises,
			&i.NeedsReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT
  id, project_id, derived_from_goal_id, content, spec, plan, status, creator, result_summary,
  work_done, now_possible, how_to_verify, surprises, needs_review,
  created_at, updated_at
FROM goals
WHERE project_id = ?
ORDER BY created_at
`

func (q *Queries) ListGoals(ctx context.Context, projectID int64) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoals, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.DerivedFromGoalID,
			&i.Content,
			&i.Spec,
			&i.Plan,
			&i.Status,
			&i.Creator,
			&i.ResultSummary,
			&i.WorkDone,
			&i.NowPossible,
			&i.HowToVerify,
			&i.Surprises,
			&i.NeedsReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestGoalConfirmations = `-- name: ListLatestGoalConfirmations :many
SELECT goal_id, MAX(confirmed_at) AS confirmed_at
FROM goal_confirmations
GROUP BY goal_id
`

type ListLatestGoalConfirmationsRow struct {
	GoalID      int64
	ConfirmedAt interface{}
}

func (q *Queries) ListLatestGoalConfirmations(ctx context.Context) ([]ListLatestGoalConfirmationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestGoalConfirmations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestGoalConfirmationsRow
	for rows.Next() {
		var i ListLatestGoalConfirmationsRow
		if err := rows.Scan(&i.GoalID, &i.ConfirmedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNextGoalIDs = `-- name: ListNextGoalIDs :many
SELECT next_goal_id
FROM next_goals
WHERE goal_id = ?
ORDER BY next_goal_id
`

func (q *Queries) ListNextGoalIDs(ctx context.Context, goalID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listNextGoalIDs, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var next_goal_id int64
		if err := rows.Scan(&next_goal_id); err != nil {
			return nil, err
		}
		items = append(items, next_goal_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNextGoals = `-- name: ListNextGoals :many
SELECT g.id, g.content, g.status
FROM next_goals AS ng
JOIN goals AS g ON g.id = ng.next_goal_id
WHERE ng.goal_id = ?
ORDER BY ng.next_goal_id
`

type ListNextGoalsRow struct {
	ID      int64
	Content string
	Status  string
}

func (q *Queries) ListNextGoals(ctx context.Context, goalID int64) ([]ListNextGoalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNextGoals, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNextGoalsRow
	for rows.Next() {
		var i ListNextGoalsRow
		if err := rows.Scan(&i.ID, &i.Content, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGoalActive = `-- name: MarkGoalActive :execresult
UPDATE goals SET status = 'active', updated_at = ?
WHERE id = ? AND status = 'proposed'
`

type MarkGoalActiveParams struct {
	UpdatedAt string
	ID        int64
}

func (q *Queries) MarkGoalActive(ctx context.Context, arg MarkGoalActiveParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markGoalActive, arg.UpdatedAt, arg.ID)
}

const markGoalDropped = `-- name: MarkGoalDropped :execresult
UPDATE goals SET status = 'dropped', updated_at = ?
WHERE id = ? AND status = 'proposed'
`

type MarkGoalDroppedParams struct {
	UpdatedAt string
	ID        int64
}

func (q *Queries) MarkGoalDropped(ctx context.Context, arg MarkGoalDroppedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markGoalDropped, arg.UpdatedAt, arg.ID)
}

const rejectGoalApprovalDecision = `-- name: RejectGoalApprovalDecision :execresult
UPDATE decisions SET status = 'answered', answer_label = 'reject',
  answer_text = ?, answered_at = ?
WHERE id = ? AND kind = 'goal_approval' AND status = 'open'
`

type RejectGoalApprovalDecisionParams struct {
	AnswerText string
	AnsweredAt sql.NullString
	ID         int64
}

func (q *Queries) RejectGoalApprovalDecision(ctx context.Context, arg RejectGoalApprovalDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, rejectGoalApprovalDecision, arg.AnswerText, arg.AnsweredAt, arg.ID)
}

const rejectGoalReviewDecision = `-- name: RejectGoalReviewDecision :execresult
UPDATE decisions
SET status = 'answered', answer_label = 'reject', answer_text = ?, answered_at = ?
WHERE id = ? AND kind = 'goal_review' AND status = 'open'
`

type RejectGoalReviewDecisionParams struct {
	AnswerText string
	AnsweredAt sql.NullString
	ID         int64
}

func (q *Queries) RejectGoalReviewDecision(ctx context.Context, arg RejectGoalReviewDecisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, rejectGoalReviewDecision, arg.AnswerText, arg.AnsweredAt, arg.ID)
}

const setGoalDerivedFrom = `-- name: SetGoalDerivedFrom :execresult
UPDATE goals SET derived_from_goal_id = ?, updated_at = ?
WHERE id = ?
`

type SetGoalDerivedFromParams struct {
	DerivedFromGoalID sql.NullInt64
	UpdatedAt         string
	ID                int64
}

func (q *Queries) SetGoalDerivedFrom(ctx context.Context, arg SetGoalDerivedFromParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setGoalDerivedFrom, arg.DerivedFromGoalID, arg.UpdatedAt, arg.ID)
}

const updateGoalCompletionReport = `-- name: UpdateGoalCompletionReport :execresult
UPDATE goals SET
  result_summary = ?,
  work_done = ?, now_possible = ?, how_to_verify = ?,
  surprises = ?, needs_review = ?, updated_at = ?
WHERE id = ? AND status = 'active'
`

type UpdateGoalCompletionReportParams struct {
	ResultSummary string
	WorkDone      string
	NowPossible   string
	HowToVerify   string
	Surprises     string
	NeedsReview   string
	UpdatedAt     string
	ID            int64
}

func (q *Queries) UpdateGoalCompletionReport(ctx context.Context, arg UpdateGoalCompletionReportParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateGoalCompletionReport,
		arg.ResultSummary,
		arg.WorkDone,
		arg.NowPossible,
		arg.HowToVerify,
		arg.Surprises,
		arg.NeedsReview,
		arg.UpdatedAt,
		arg.ID,
	)
}

const updateGoalContent = `-- name: UpdateGoalContent :execresult
UPDATE goals SET content = ?, updated_at = ?
WHERE id = ? AND status = 'proposed'
`

type UpdateGoalContentParams struct {
	Content   string
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdateGoalContent(ctx context.Context, arg UpdateGoalContentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateGoalContent, arg.Content, arg.UpdatedAt, arg.ID)
}

const updateGoalRequestReport = `-- name: UpdateGoalRequestReport :execresult
UPDATE goals SET spec = ?, plan = ?, updated_at = ? WHERE id = ?
`

type UpdateGoalRequestReportParams struct {
	Spec      string
	Plan      string
	UpdatedAt string
	ID        int64
}

func (q *Queries) UpdateGoalRequestReport(ctx context.Context, arg UpdateGoalRequestReportParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateGoalRequestReport,
		arg.Spec,
		arg.Plan,
		arg.UpdatedAt,
		arg.ID,
	)
}

const withdrawActiveGoal = `-- name: WithdrawActiveGoal :execresult
UPDATE goals SET status = 'dropped', result_summary = ?, updated_at = ?
WHERE id = ? AND status = 'active'
`

type WithdrawActiveGoalParams struct {
	ResultSummary string
	UpdatedAt     string
	ID            int64
}

func (q *Queries) WithdrawActiveGoal(ctx context.Context, arg WithdrawActiveGoalParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, withdrawActiveGoal, arg.ResultSummary, arg.UpdatedAt, arg.ID)
}

const withdrawProposedGoal = `-- name: WithdrawProposedGoal :execresult
UPDATE goals SET status = 'dropped', result_summary = ?, updated_at = ?
WHERE id = ? AND status = 'proposed'
`

type WithdrawProposedGoalParams struct {
	ResultSummary string
	UpdatedAt     string
	ID            int64
}

func (q *Queries) WithdrawProposedGoal(ctx context.Context, arg WithdrawProposedGoalParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, withdrawProposedGoal, arg.ResultSummary, arg.UpdatedAt, arg.ID)
}
