// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: handoff_entry.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countGoalHandoffRequestEntries = `-- name: CountGoalHandoffRequestEntries :one
SELECT COUNT(*)
FROM goal_handoff_entries
WHERE handoff_id = ? AND kind = 'request'
`

func (q *Queries) CountGoalHandoffRequestEntries(ctx context.Context, handoffID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGoalHandoffRequestEntries, handoffID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTaskHandoffRequestEntries = `-- name: CountTaskHandoffRequestEntries :one
SELECT COUNT(*)
FROM task_handoff_entries
WHERE handoff_id = ? AND kind = 'request'
`

func (q *Queries) CountTaskHandoffRequestEntries(ctx context.Context, handoffID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskHandoffRequestEntries, handoffID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGoalHandoffEntry = `-- name: CreateGoalHandoffEntry :exec
INSERT INTO goal_handoff_entries (
  entry_id, handoff_id, sequence, kind, body, author_session_id,
  relates_to, source, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGoalHandoffEntryParams struct {
	EntryID         string
	HandoffID       string
	Sequence        int64
	Kind            string
	Body            string
	AuthorSessionID sql.NullInt64
	RelatesTo       sql.NullString
	Source          string
	CreatedAt       string
}

func (q *Queries) CreateGoalHandoffEntry(ctx context.Context, arg CreateGoalHandoffEntryParams) error {
	_, err := q.db.ExecContext(ctx, createGoalHandoffEntry,
		arg.EntryID,
		arg.HandoffID,
		arg.Sequence,
		arg.Kind,
		arg.Body,
		arg.AuthorSessionID,
		arg.RelatesTo,
		arg.Source,
		arg.CreatedAt,
	)
	return err
}

const createTaskHandoffEntry = `-- name: CreateTaskHandoffEntry :exec
INSERT INTO task_handoff_entries (
  entry_id, handoff_id, sequence, kind, body, author_session_id,
  relates_to, source, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskHandoffEntryParams struct {
	EntryID         string
	HandoffID       string
	Sequence        int64
	Kind            string
	Body            string
	AuthorSessionID sql.NullInt64
	RelatesTo       sql.NullString
	Source          string
	CreatedAt       string
}

func (q *Queries) CreateTaskHandoffEntry(ctx context.Context, arg CreateTaskHandoffEntryParams) error {
	_, err := q.db.ExecContext(ctx, createTaskHandoffEntry,
		arg.EntryID,
		arg.HandoffID,
		arg.Sequence,
		arg.Kind,
		arg.Body,
		arg.AuthorSessionID,
		arg.RelatesTo,
		arg.Source,
		arg.CreatedAt,
	)
	return err
}

const getGoalHandoffEntryState = `-- name: GetGoalHandoffEntryState :one
SELECT requested_by, received_by, completed_report_at
FROM goal_handoffs
WHERE id = ?
`

type GetGoalHandoffEntryStateRow struct {
	RequestedBy       sql.NullInt64
	ReceivedBy        sql.NullInt64
	CompletedReportAt sql.NullString
}

func (q *Queries) GetGoalHandoffEntryState(ctx context.Context, id string) (GetGoalHandoffEntryStateRow, error) {
	row := q.db.QueryRowContext(ctx, getGoalHandoffEntryState, id)
	var i GetGoalHandoffEntryStateRow
	err := row.Scan(&i.RequestedBy, &i.ReceivedBy, &i.CompletedReportAt)
	return i, err
}

const getTaskHandoffEntryState = `-- name: GetTaskHandoffEntryState :one
SELECT requested_by, received_by, completed_report_at
FROM task_handoffs
WHERE id = ?
`

type GetTaskHandoffEntryStateRow struct {
	RequestedBy       sql.NullInt64
	ReceivedBy        sql.NullInt64
	CompletedReportAt sql.NullString
}

func (q *Queries) GetTaskHandoffEntryState(ctx context.Context, id string) (GetTaskHandoffEntryStateRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskHandoffEntryState, id)
	var i GetTaskHandoffEntryStateRow
	err := row.Scan(&i.RequestedBy, &i.ReceivedBy, &i.CompletedReportAt)
	return i, err
}

const goalHandoffEntryExists = `-- name: GoalHandoffEntryExists :one
SELECT COUNT(*)
FROM goal_handoff_entries
WHERE handoff_id = ? AND entry_id = ?
`

type GoalHandoffEntryExistsParams struct {
	HandoffID string
	EntryID   string
}

func (q *Queries) GoalHandoffEntryExists(ctx context.Context, arg GoalHandoffEntryExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, goalHandoffEntryExists, arg.HandoffID, arg.EntryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listGoalHandoffEntries = `-- name: ListGoalHandoffEntries :many
SELECT entry_id, handoff_id, sequence, kind, body, author_session_id,
       relates_to, source, created_at
FROM goal_handoff_entries
WHERE handoff_id = ?1 AND sequence > ?2
ORDER BY sequence ASC
LIMIT ?3
`

type ListGoalHandoffEntriesParams struct {
	HandoffID string
	Cursor    int64
	Limit     int64
}

func (q *Queries) ListGoalHandoffEntries(ctx context.Context, arg ListGoalHandoffEntriesParams) ([]GoalHandoffEntry, error) {
	rows, err := q.db.QueryContext(ctx, listGoalHandoffEntries, arg.HandoffID, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalHandoffEntry
	for rows.Next() {
		var i GoalHandoffEntry
		if err := rows.Scan(
			&i.EntryID,
			&i.HandoffID,
			&i.Sequence,
			&i.Kind,
			&i.Body,
			&i.AuthorSessionID,
			&i.RelatesTo,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskHandoffEntries = `-- name: ListTaskHandoffEntries :many
SELECT entry_id, handoff_id, sequence, kind, body, author_session_id,
       relates_to, source, created_at
FROM task_handoff_entries
WHERE handoff_id = ?1 AND sequence > ?2
ORDER BY sequence ASC
LIMIT ?3
`

type ListTaskHandoffEntriesParams struct {
	HandoffID string
	Cursor    int64
	Limit     int64
}

func (q *Queries) ListTaskHandoffEntries(ctx context.Context, arg ListTaskHandoffEntriesParams) ([]TaskHandoffEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTaskHandoffEntries, arg.HandoffID, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskHandoffEntry
	for rows.Next() {
		var i TaskHandoffEntry
		if err := rows.Scan(
			&i.EntryID,
			&i.HandoffID,
			&i.Sequence,
			&i.Kind,
			&i.Body,
			&i.AuthorSessionID,
			&i.RelatesTo,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxGoalHandoffEntrySequence = `-- name: MaxGoalHandoffEntrySequence :one
SELECT COALESCE(MAX(sequence), 0) + 1
FROM goal_handoff_entries
WHERE handoff_id = ?
`

func (q *Queries) MaxGoalHandoffEntrySequence(ctx context.Context, handoffID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxGoalHandoffEntrySequence, handoffID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const maxTaskHandoffEntrySequence = `-- name: MaxTaskHandoffEntrySequence :one
SELECT COALESCE(MAX(sequence), 0) + 1
FROM task_handoff_entries
WHERE handoff_id = ?
`

func (q *Queries) MaxTaskHandoffEntrySequence(ctx context.Context, handoffID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxTaskHandoffEntrySequence, handoffID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const taskHandoffEntryExists = `-- name: TaskHandoffEntryExists :one
SELECT COUNT(*)
FROM task_handoff_entries
WHERE handoff_id = ? AND entry_id = ?
`

type TaskHandoffEntryExistsParams struct {
	HandoffID string
	EntryID   string
}

func (q *Queries) TaskHandoffEntryExists(ctx context.Context, arg TaskHandoffEntryExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, taskHandoffEntryExists, arg.HandoffID, arg.EntryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
