// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: handoff_recovery.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createHandoffRecovery = `-- name: CreateHandoffRecovery :one
INSERT INTO handoff_recoveries (
  handoff_kind, handoff_id, goal_id, task_id, recovered_phase,
  stale_session_id, proof_kind, discard_decision_id, recovered_by,
  replacement_id, reason, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(handoff_kind, handoff_id, recovered_phase, stale_session_id)
DO UPDATE SET id = handoff_recoveries.id
RETURNING id
`

type CreateHandoffRecoveryParams struct {
	HandoffKind       string
	HandoffID         string
	GoalID            sql.NullInt64
	TaskID            sql.NullInt64
	RecoveredPhase    string
	StaleSessionID    int64
	ProofKind         string
	DiscardDecisionID sql.NullInt64
	RecoveredBy       int64
	ReplacementID     sql.NullString
	Reason            string
	CreatedAt         string
}

func (q *Queries) CreateHandoffRecovery(ctx context.Context, arg CreateHandoffRecoveryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createHandoffRecovery,
		arg.HandoffKind,
		arg.HandoffID,
		arg.GoalID,
		arg.TaskID,
		arg.RecoveredPhase,
		arg.StaleSessionID,
		arg.ProofKind,
		arg.DiscardDecisionID,
		arg.RecoveredBy,
		arg.ReplacementID,
		arg.Reason,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const discardAgentSession = `-- name: DiscardAgentSession :execresult
UPDATE agent_sessions
SET discarded_at = ?, discarded_by = ?, discarded_decision_id = ?, discard_reason = ?
WHERE id = ? AND project_id = ? AND discarded_at IS NULL
`

type DiscardAgentSessionParams struct {
	DiscardedAt         sql.NullString
	DiscardedBy         sql.NullInt64
	DiscardedDecisionID sql.NullInt64
	DiscardReason       string
	ID                  int64
	ProjectID           sql.NullInt64
}

func (q *Queries) DiscardAgentSession(ctx context.Context, arg DiscardAgentSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, discardAgentSession,
		arg.DiscardedAt,
		arg.DiscardedBy,
		arg.DiscardedDecisionID,
		arg.DiscardReason,
		arg.ID,
		arg.ProjectID,
	)
}

const getAgentSessionRecovery = `-- name: GetAgentSessionRecovery :one
SELECT id, project_id, pid, started_at, discarded_at, discarded_by,
       discarded_decision_id, discard_reason
FROM agent_sessions
WHERE id = ?
`

type GetAgentSessionRecoveryRow struct {
	ID                  int64
	ProjectID           sql.NullInt64
	Pid                 int64
	StartedAt           string
	DiscardedAt         sql.NullString
	DiscardedBy         sql.NullInt64
	DiscardedDecisionID sql.NullInt64
	DiscardReason       string
}

func (q *Queries) GetAgentSessionRecovery(ctx context.Context, id int64) (GetAgentSessionRecoveryRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionRecovery, id)
	var i GetAgentSessionRecoveryRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Pid,
		&i.StartedAt,
		&i.DiscardedAt,
		&i.DiscardedBy,
		&i.DiscardedDecisionID,
		&i.DiscardReason,
	)
	return i, err
}

const getHandoffRecovery = `-- name: GetHandoffRecovery :one
SELECT id, handoff_kind, handoff_id, goal_id, task_id, recovered_phase,
       stale_session_id, proof_kind, discard_decision_id, recovered_by,
       replacement_id, reason, created_at
FROM handoff_recoveries
WHERE handoff_kind = ?
  AND handoff_id = ?
  AND recovered_phase = ?
  AND stale_session_id = ?
`

type GetHandoffRecoveryParams struct {
	HandoffKind    string
	HandoffID      string
	RecoveredPhase string
	StaleSessionID int64
}

func (q *Queries) GetHandoffRecovery(ctx context.Context, arg GetHandoffRecoveryParams) (HandoffRecovery, error) {
	row := q.db.QueryRowContext(ctx, getHandoffRecovery,
		arg.HandoffKind,
		arg.HandoffID,
		arg.RecoveredPhase,
		arg.StaleSessionID,
	)
	var i HandoffRecovery
	err := row.Scan(
		&i.ID,
		&i.HandoffKind,
		&i.HandoffID,
		&i.GoalID,
		&i.TaskID,
		&i.RecoveredPhase,
		&i.StaleSessionID,
		&i.ProofKind,
		&i.DiscardDecisionID,
		&i.RecoveredBy,
		&i.ReplacementID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listHandoffRecoveriesForGoal = `-- name: ListHandoffRecoveriesForGoal :many
SELECT id, handoff_kind, handoff_id, goal_id, task_id, recovered_phase,
       stale_session_id, proof_kind, discard_decision_id, recovered_by,
       replacement_id, reason, created_at
FROM handoff_recoveries
WHERE goal_id = ?
ORDER BY created_at, id
`

func (q *Queries) ListHandoffRecoveriesForGoal(ctx context.Context, goalID sql.NullInt64) ([]HandoffRecovery, error) {
	rows, err := q.db.QueryContext(ctx, listHandoffRecoveriesForGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HandoffRecovery
	for rows.Next() {
		var i HandoffRecovery
		if err := rows.Scan(
			&i.ID,
			&i.HandoffKind,
			&i.HandoffID,
			&i.GoalID,
			&i.TaskID,
			&i.RecoveredPhase,
			&i.StaleSessionID,
			&i.ProofKind,
			&i.DiscardDecisionID,
			&i.RecoveredBy,
			&i.ReplacementID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHandoffRecoveriesForTask = `-- name: ListHandoffRecoveriesForTask :many
SELECT id, handoff_kind, handoff_id, goal_id, task_id, recovered_phase,
       stale_session_id, proof_kind, discard_decision_id, recovered_by,
       replacement_id, reason, created_at
FROM handoff_recoveries
WHERE task_id = ?
ORDER BY created_at, id
`

func (q *Queries) ListHandoffRecoveriesForTask(ctx context.Context, taskID sql.NullInt64) ([]HandoffRecovery, error) {
	rows, err := q.db.QueryContext(ctx, listHandoffRecoveriesForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HandoffRecovery
	for rows.Next() {
		var i HandoffRecovery
		if err := rows.Scan(
			&i.ID,
			&i.HandoffKind,
			&i.HandoffID,
			&i.GoalID,
			&i.TaskID,
			&i.RecoveredPhase,
			&i.StaleSessionID,
			&i.ProofKind,
			&i.DiscardDecisionID,
			&i.RecoveredBy,
			&i.ReplacementID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
