// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: handoff_entry.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countGoalHandoffRequestEntries = `-- name: CountGoalHandoffRequestEntries :one
SELECT COUNT(*)
FROM goal_handoff_entries
WHERE handoff_id = ? AND kind = 'request'
`

func (q *Queries) CountGoalHandoffRequestEntries(ctx context.Context, handoffID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGoalHandoffRequestEntries, handoffID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTaskHandoffRequestEntries = `-- name: CountTaskHandoffRequestEntries :one
SELECT COUNT(*)
FROM task_handoff_entries
WHERE handoff_id = ? AND kind = 'request'
`

func (q *Queries) CountTaskHandoffRequestEntries(ctx context.Context, handoffID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskHandoffRequestEntries, handoffID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGoalHandoffEntry = `-- name: CreateGoalHandoffEntry :one
INSERT INTO goal_handoff_entries (
  handoff_id, kind, body, author_session_id, in_reply_to_id, created_at
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateGoalHandoffEntryParams struct {
	HandoffID       string
	Kind            string
	Body            string
	AuthorSessionID sql.NullInt64
	InReplyToID     sql.NullInt64
	CreatedAt       string
}

func (q *Queries) CreateGoalHandoffEntry(ctx context.Context, arg CreateGoalHandoffEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createGoalHandoffEntry,
		arg.HandoffID,
		arg.Kind,
		arg.Body,
		arg.AuthorSessionID,
		arg.InReplyToID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTaskHandoffEntry = `-- name: CreateTaskHandoffEntry :one
INSERT INTO task_handoff_entries (
  handoff_id, kind, body, author_session_id, in_reply_to_id, created_at
)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateTaskHandoffEntryParams struct {
	HandoffID       string
	Kind            string
	Body            string
	AuthorSessionID sql.NullInt64
	InReplyToID     sql.NullInt64
	CreatedAt       string
}

func (q *Queries) CreateTaskHandoffEntry(ctx context.Context, arg CreateTaskHandoffEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createTaskHandoffEntry,
		arg.HandoffID,
		arg.Kind,
		arg.Body,
		arg.AuthorSessionID,
		arg.InReplyToID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getGoalHandoffEntryState = `-- name: GetGoalHandoffEntryState :one
SELECT requested_by, received_by, completed_report_at
FROM goal_handoffs
WHERE id = ?
`

type GetGoalHandoffEntryStateRow struct {
	RequestedBy       sql.NullInt64
	ReceivedBy        sql.NullInt64
	CompletedReportAt sql.NullString
}

func (q *Queries) GetGoalHandoffEntryState(ctx context.Context, id string) (GetGoalHandoffEntryStateRow, error) {
	row := q.db.QueryRowContext(ctx, getGoalHandoffEntryState, id)
	var i GetGoalHandoffEntryStateRow
	err := row.Scan(&i.RequestedBy, &i.ReceivedBy, &i.CompletedReportAt)
	return i, err
}

const getTaskHandoffEntryState = `-- name: GetTaskHandoffEntryState :one
SELECT requested_by, received_by, completed_report_at
FROM task_handoffs
WHERE id = ?
`

type GetTaskHandoffEntryStateRow struct {
	RequestedBy       sql.NullInt64
	ReceivedBy        sql.NullInt64
	CompletedReportAt sql.NullString
}

func (q *Queries) GetTaskHandoffEntryState(ctx context.Context, id string) (GetTaskHandoffEntryStateRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskHandoffEntryState, id)
	var i GetTaskHandoffEntryStateRow
	err := row.Scan(&i.RequestedBy, &i.ReceivedBy, &i.CompletedReportAt)
	return i, err
}

const goalHandoffEntryExists = `-- name: GoalHandoffEntryExists :one
SELECT COUNT(*)
FROM goal_handoff_entries
WHERE handoff_id = ? AND id = ?
`

type GoalHandoffEntryExistsParams struct {
	HandoffID string
	ID        int64
}

func (q *Queries) GoalHandoffEntryExists(ctx context.Context, arg GoalHandoffEntryExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, goalHandoffEntryExists, arg.HandoffID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listGoalHandoffEntries = `-- name: ListGoalHandoffEntries :many
SELECT id, handoff_id, kind, body, author_session_id, in_reply_to_id, created_at
FROM goal_handoff_entries
WHERE handoff_id = ?1 AND id > ?2
ORDER BY id ASC
LIMIT ?3
`

type ListGoalHandoffEntriesParams struct {
	HandoffID string
	Cursor    int64
	Limit     int64
}

func (q *Queries) ListGoalHandoffEntries(ctx context.Context, arg ListGoalHandoffEntriesParams) ([]GoalHandoffEntry, error) {
	rows, err := q.db.QueryContext(ctx, listGoalHandoffEntries, arg.HandoffID, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalHandoffEntry
	for rows.Next() {
		var i GoalHandoffEntry
		if err := rows.Scan(
			&i.ID,
			&i.HandoffID,
			&i.Kind,
			&i.Body,
			&i.AuthorSessionID,
			&i.InReplyToID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskHandoffEntries = `-- name: ListTaskHandoffEntries :many
SELECT id, handoff_id, kind, body, author_session_id, in_reply_to_id, created_at
FROM task_handoff_entries
WHERE handoff_id = ?1 AND id > ?2
ORDER BY id ASC
LIMIT ?3
`

type ListTaskHandoffEntriesParams struct {
	HandoffID string
	Cursor    int64
	Limit     int64
}

func (q *Queries) ListTaskHandoffEntries(ctx context.Context, arg ListTaskHandoffEntriesParams) ([]TaskHandoffEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTaskHandoffEntries, arg.HandoffID, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskHandoffEntry
	for rows.Next() {
		var i TaskHandoffEntry
		if err := rows.Scan(
			&i.ID,
			&i.HandoffID,
			&i.Kind,
			&i.Body,
			&i.AuthorSessionID,
			&i.InReplyToID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskHandoffEntryExists = `-- name: TaskHandoffEntryExists :one
SELECT COUNT(*)
FROM task_handoff_entries
WHERE handoff_id = ? AND id = ?
`

type TaskHandoffEntryExistsParams struct {
	HandoffID string
	ID        int64
}

func (q *Queries) TaskHandoffEntryExists(ctx context.Context, arg TaskHandoffEntryExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, taskHandoffEntryExists, arg.HandoffID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
