// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type AgentSession struct {
	ID           string
	ProjectID    sql.NullString
	RegisteredAt string
	Pid          int64
	StartedAt    string
}

type Decision struct {
	ID               string
	GoalID           string
	TaskID           sql.NullString
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   string
	CreatedAt        string
}

type Goal struct {
	ID            string
	ProjectID     string
	Title         string
	Description   string
	Status        string
	ResultSummary string
	WorkDone      string
	NowPossible   string
	HowToVerify   string
	Surprises     string
	NeedsReview   string
	NextSteps     string
	CreatedAt     string
	UpdatedAt     string
}

type Project struct {
	ID        string
	Name      string
	RootPath  string
	CreatedAt string
}

type Task struct {
	ID          string
	GoalID      string
	Title       string
	Description string
	Status      string
	Agent       string
	Files       string
	SortOrder   int64
	DeclareKey  string
	ClaimedBy   string
	ClaimedAt   sql.NullString
	CreatedAt   string
	UpdatedAt   string
}
