// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type AgentSession struct {
	ID           int64
	ProjectID    sql.NullInt64
	RegisteredAt string
	Pid          int64
	StartedAt    string
	SessionKey   string
}

type Decision struct {
	ID               int64
	GoalID           int64
	TaskID           sql.NullInt64
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   int64
	CreatedAt        string
}

type Goal struct {
	ID                int64
	ProjectID         int64
	DerivedFromGoalID sql.NullInt64
	Content           string
	Status            string
	Creator           string
	ResultSummary     string
	WorkDone          string
	NowPossible       string
	HowToVerify       string
	Surprises         string
	NeedsReview       string
	NextSteps         string
	CreatedAt         string
	UpdatedAt         string
}

type GoalHandoff struct {
	ID                string
	GoalID            int64
	RequestedBy       sql.NullInt64
	ReceivedBy        sql.NullInt64
	RequestedAt       sql.NullString
	ReceivedAt        sql.NullString
	CompletedReportAt sql.NullString
	RequestReport     sql.NullString
	CompleteReport    sql.NullString
}

type Project struct {
	ID        int64
	Name      string
	RootPath  string
	CreatedAt string
	ClaimedBy int64
	ClaimedAt sql.NullString
}

type SchemaMigration struct {
	Filename  string
	AppliedAt string
}

type Task struct {
	ID           int64
	GoalID       int64
	Title        string
	Description  string
	Status       string
	Agent        string
	SortOrder    int64
	DeclareKey   string
	SnoozedUntil sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

type TaskCommit struct {
	TaskID       int64
	Sha          string
	Subject      string
	FilesChanged int64
	Insertions   int64
	Deletions    int64
	CreatedAt    string
}

type TaskHandoff struct {
	ID                string
	TaskID            int64
	RequestedBy       sql.NullInt64
	ReceivedBy        sql.NullInt64
	RequestedAt       sql.NullString
	ReceivedAt        sql.NullString
	CompletedReportAt sql.NullString
	RequestReport     sql.NullString
	CompleteReport    sql.NullString
}
