// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type AgentSession struct {
	ID           string
	ProjectID    sql.NullString
	RegisteredAt string
	Pid          int64
	StartedAt    string
}

type Decision struct {
	ID               string
	GoalID           string
	TaskID           sql.NullString
	Kind             string
	Question         string
	Options          string
	Status           string
	DefaultOption    string
	DefaultAfterMs   sql.NullInt64
	DefaultAppliedAt sql.NullString
	AnswerLabel      string
	AnswerText       string
	AnsweredAt       sql.NullString
	AppliedAt        sql.NullString
	AgentSessionID   string
	CreatedAt        string
}

type Goal struct {
	ID                string
	ProjectID         string
	DerivedFromGoalID sql.NullString
	Content           string
	Status            string
	Creator           string
	ResultSummary     string
	WorkDone          string
	NowPossible       string
	HowToVerify       string
	Surprises         string
	NeedsReview       string
	NextSteps         string
	ClaimedBy         string
	ClaimedAt         sql.NullString
	CreatedAt         string
	UpdatedAt         string
}

type Project struct {
	ID        string
	Name      string
	RootPath  string
	CreatedAt string
	ClaimedBy string
	ClaimedAt sql.NullString
}

type Task struct {
	ID           string
	GoalID       string
	Title        string
	Description  string
	Status       string
	Agent        string
	Files        string
	SortOrder    int64
	DeclareKey   string
	ClaimedBy    string
	ClaimedAt    sql.NullString
	SnoozedUntil sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

type TaskCommit struct {
	TaskID       string
	Sha          string
	Subject      string
	FilesChanged int64
	Insertions   int64
	Deletions    int64
	CreatedAt    string
}

type TaskHandoff struct {
	ID                string
	TaskID            string
	RequestedBy       sql.NullString
	ReceivedBy        sql.NullString
	RequestedAt       sql.NullString
	ReceivedAt        sql.NullString
	CompletedReportAt sql.NullString
}
