// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor_assignment.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getMonitorCommanderProjectID = `-- name: GetMonitorCommanderProjectID :one
SELECT id
FROM projects
WHERE claimed_by = ?1
ORDER BY created_at, id
LIMIT 1
`

func (q *Queries) GetMonitorCommanderProjectID(ctx context.Context, agentSessionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMonitorCommanderProjectID, agentSessionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMonitorSubcommanderAssignment = `-- name: GetMonitorSubcommanderAssignment :one
SELECT g.project_id, gh.goal_id
FROM goal_handoffs AS gh
JOIN goals AS g ON g.id = gh.goal_id
WHERE gh.received_by = ?1
  AND gh.received_at IS NOT NULL
  AND gh.completed_report_at IS NULL
  AND gh.recovered_at IS NULL
ORDER BY g.created_at, g.id
LIMIT 1
`

type GetMonitorSubcommanderAssignmentRow struct {
	ProjectID int64
	GoalID    int64
}

func (q *Queries) GetMonitorSubcommanderAssignment(ctx context.Context, agentSessionID sql.NullInt64) (GetMonitorSubcommanderAssignmentRow, error) {
	row := q.db.QueryRowContext(ctx, getMonitorSubcommanderAssignment, agentSessionID)
	var i GetMonitorSubcommanderAssignmentRow
	err := row.Scan(&i.ProjectID, &i.GoalID)
	return i, err
}

const listMonitorExecutorAssignments = `-- name: ListMonitorExecutorAssignments :many
SELECT g.project_id, t.goal_id, th.task_id
FROM task_handoffs AS th
JOIN tasks AS t ON t.id = th.task_id
JOIN goals AS g ON g.id = t.goal_id
WHERE th.received_by = ?1
  AND th.received_at IS NOT NULL
  AND th.completed_report_at IS NULL
  AND th.recovered_at IS NULL
ORDER BY th.task_id
`

type ListMonitorExecutorAssignmentsRow struct {
	ProjectID int64
	GoalID    int64
	TaskID    int64
}

func (q *Queries) ListMonitorExecutorAssignments(ctx context.Context, agentSessionID sql.NullInt64) ([]ListMonitorExecutorAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorExecutorAssignments, agentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonitorExecutorAssignmentsRow
	for rows.Next() {
		var i ListMonitorExecutorAssignmentsRow
		if err := rows.Scan(&i.ProjectID, &i.GoalID, &i.TaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
