// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor_health.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countLiveMonitorsForScope = `-- name: CountLiveMonitorsForScope :one
SELECT COUNT(*)
FROM monitor_health
WHERE project_id = ?
  AND role = ?
  AND goal_id IS ?
  AND last_seen_at >= ?
  AND stopped_at IS NULL
`

type CountLiveMonitorsForScopeParams struct {
	ProjectID  int64
	Role       string
	GoalID     sql.NullInt64
	LastSeenAt string
}

func (q *Queries) CountLiveMonitorsForScope(ctx context.Context, arg CountLiveMonitorsForScopeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveMonitorsForScope,
		arg.ProjectID,
		arg.Role,
		arg.GoalID,
		arg.LastSeenAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMonitorHealth = `-- name: ListMonitorHealth :many
SELECT monitor_id, agent_key, scope_key, agent_session_id, cwd, role, project_id, goal_id, task_id, pid,
       process_started_at, state, reason, transitioned_at, last_seen_at, stopped_at
FROM monitor_health
WHERE project_id = ? AND last_seen_at >= ? AND stopped_at IS NULL
ORDER BY transitioned_at DESC, monitor_id
`

type ListMonitorHealthParams struct {
	ProjectID  int64
	LastSeenAt string
}

type ListMonitorHealthRow struct {
	MonitorID        string
	AgentKey         string
	ScopeKey         string
	AgentSessionID   int64
	Cwd              string
	Role             string
	ProjectID        int64
	GoalID           sql.NullInt64
	TaskID           sql.NullInt64
	Pid              int64
	ProcessStartedAt string
	State            string
	Reason           string
	TransitionedAt   string
	LastSeenAt       string
	StoppedAt        sql.NullString
}

func (q *Queries) ListMonitorHealth(ctx context.Context, arg ListMonitorHealthParams) ([]ListMonitorHealthRow, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorHealth, arg.ProjectID, arg.LastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonitorHealthRow
	for rows.Next() {
		var i ListMonitorHealthRow
		if err := rows.Scan(
			&i.MonitorID,
			&i.AgentKey,
			&i.ScopeKey,
			&i.AgentSessionID,
			&i.Cwd,
			&i.Role,
			&i.ProjectID,
			&i.GoalID,
			&i.TaskID,
			&i.Pid,
			&i.ProcessStartedAt,
			&i.State,
			&i.Reason,
			&i.TransitionedAt,
			&i.LastSeenAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorHealthHistory = `-- name: ListMonitorHealthHistory :many
SELECT monitor_id, agent_key, scope_key, agent_session_id, cwd, role, project_id, goal_id, task_id, pid,
       process_started_at, state, reason, transitioned_at, last_seen_at, stopped_at
FROM monitor_health
WHERE project_id = ?
ORDER BY last_seen_at DESC, monitor_id
`

type ListMonitorHealthHistoryRow struct {
	MonitorID        string
	AgentKey         string
	ScopeKey         string
	AgentSessionID   int64
	Cwd              string
	Role             string
	ProjectID        int64
	GoalID           sql.NullInt64
	TaskID           sql.NullInt64
	Pid              int64
	ProcessStartedAt string
	State            string
	Reason           string
	TransitionedAt   string
	LastSeenAt       string
	StoppedAt        sql.NullString
}

func (q *Queries) ListMonitorHealthHistory(ctx context.Context, projectID int64) ([]ListMonitorHealthHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorHealthHistory, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonitorHealthHistoryRow
	for rows.Next() {
		var i ListMonitorHealthHistoryRow
		if err := rows.Scan(
			&i.MonitorID,
			&i.AgentKey,
			&i.ScopeKey,
			&i.AgentSessionID,
			&i.Cwd,
			&i.Role,
			&i.ProjectID,
			&i.GoalID,
			&i.TaskID,
			&i.Pid,
			&i.ProcessStartedAt,
			&i.State,
			&i.Reason,
			&i.TransitionedAt,
			&i.LastSeenAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneMonitorHealth = `-- name: PruneMonitorHealth :exec
DELETE FROM monitor_health
WHERE last_seen_at < ?1
   OR (stopped_at IS NOT NULL AND stopped_at < ?1)
`

func (q *Queries) PruneMonitorHealth(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, pruneMonitorHealth, cutoff)
	return err
}

const stopMonitorHealth = `-- name: StopMonitorHealth :execresult
UPDATE monitor_health
SET state = 'stopped', reason = 'stopped', stopped_at = ?,
    transitioned_at = ?, last_seen_at = ?
WHERE monitor_id = ?
`

type StopMonitorHealthParams struct {
	StoppedAt      sql.NullString
	TransitionedAt string
	LastSeenAt     string
	MonitorID      string
}

func (q *Queries) StopMonitorHealth(ctx context.Context, arg StopMonitorHealthParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, stopMonitorHealth,
		arg.StoppedAt,
		arg.TransitionedAt,
		arg.LastSeenAt,
		arg.MonitorID,
	)
}

const upsertMonitorHealth = `-- name: UpsertMonitorHealth :exec
INSERT INTO monitor_health (
  monitor_id, agent_key, scope_key, agent_session_id, cwd, role, project_id, goal_id, task_id, pid,
  process_started_at, state, reason, transitioned_at, last_seen_at, stopped_at
)
VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6,
  ?7, ?8, ?9, ?10,
  ?11, ?12, ?13,
  ?14, ?15, NULL
)
ON CONFLICT(monitor_id) DO UPDATE SET
  agent_key = excluded.agent_key,
  scope_key = excluded.scope_key,
  agent_session_id = excluded.agent_session_id,
  cwd = excluded.cwd,
  role = excluded.role,
  project_id = excluded.project_id,
  goal_id = excluded.goal_id,
  task_id = excluded.task_id,
  pid = excluded.pid,
  process_started_at = excluded.process_started_at,
  state = excluded.state,
  reason = excluded.reason,
  transitioned_at = CASE WHEN excluded.transitioned_at = '' THEN monitor_health.transitioned_at ELSE excluded.transitioned_at END,
  last_seen_at = excluded.last_seen_at,
  stopped_at = NULL
`

type UpsertMonitorHealthParams struct {
	MonitorID        string
	AgentKey         string
	ScopeKey         string
	AgentSessionID   int64
	Cwd              string
	Role             string
	ProjectID        int64
	GoalID           sql.NullInt64
	TaskID           sql.NullInt64
	Pid              int64
	ProcessStartedAt string
	State            string
	Reason           string
	TransitionedAt   string
	LastSeenAt       string
}

func (q *Queries) UpsertMonitorHealth(ctx context.Context, arg UpsertMonitorHealthParams) error {
	_, err := q.db.ExecContext(ctx, upsertMonitorHealth,
		arg.MonitorID,
		arg.AgentKey,
		arg.ScopeKey,
		arg.AgentSessionID,
		arg.Cwd,
		arg.Role,
		arg.ProjectID,
		arg.GoalID,
		arg.TaskID,
		arg.Pid,
		arg.ProcessStartedAt,
		arg.State,
		arg.Reason,
		arg.TransitionedAt,
		arg.LastSeenAt,
	)
	return err
}
