// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orchestration_blocker.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getOrchestrationBlocker = `-- name: GetOrchestrationBlocker :one
SELECT blocker_id, project_id, goal_id, task_id, scope_key, kind, source_id,
       generation, owner_role, instruction, opened_at, resolved_at
FROM orchestration_blockers
WHERE blocker_id = ?
`

func (q *Queries) GetOrchestrationBlocker(ctx context.Context, blockerID string) (OrchestrationBlocker, error) {
	row := q.db.QueryRowContext(ctx, getOrchestrationBlocker, blockerID)
	var i OrchestrationBlocker
	err := row.Scan(
		&i.BlockerID,
		&i.ProjectID,
		&i.GoalID,
		&i.TaskID,
		&i.ScopeKey,
		&i.Kind,
		&i.SourceID,
		&i.Generation,
		&i.OwnerRole,
		&i.Instruction,
		&i.OpenedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getOrchestrationBlockerByKey = `-- name: GetOrchestrationBlockerByKey :one
SELECT blocker_id, project_id, goal_id, task_id, scope_key, kind, source_id,
       generation, owner_role, instruction, opened_at, resolved_at
FROM orchestration_blockers
WHERE kind = ? AND source_id = ? AND generation = ?
`

type GetOrchestrationBlockerByKeyParams struct {
	Kind       string
	SourceID   string
	Generation string
}

func (q *Queries) GetOrchestrationBlockerByKey(ctx context.Context, arg GetOrchestrationBlockerByKeyParams) (OrchestrationBlocker, error) {
	row := q.db.QueryRowContext(ctx, getOrchestrationBlockerByKey, arg.Kind, arg.SourceID, arg.Generation)
	var i OrchestrationBlocker
	err := row.Scan(
		&i.BlockerID,
		&i.ProjectID,
		&i.GoalID,
		&i.TaskID,
		&i.ScopeKey,
		&i.Kind,
		&i.SourceID,
		&i.Generation,
		&i.OwnerRole,
		&i.Instruction,
		&i.OpenedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertOrchestrationBlocker = `-- name: InsertOrchestrationBlocker :exec
INSERT INTO orchestration_blockers (
    blocker_id, project_id, goal_id, task_id, scope_key, kind, source_id,
    generation, owner_role, instruction, opened_at, resolved_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL)
`

type InsertOrchestrationBlockerParams struct {
	BlockerID   string
	ProjectID   int64
	GoalID      sql.NullInt64
	TaskID      sql.NullInt64
	ScopeKey    string
	Kind        string
	SourceID    string
	Generation  string
	OwnerRole   string
	Instruction string
	OpenedAt    string
}

func (q *Queries) InsertOrchestrationBlocker(ctx context.Context, arg InsertOrchestrationBlockerParams) error {
	_, err := q.db.ExecContext(ctx, insertOrchestrationBlocker,
		arg.BlockerID,
		arg.ProjectID,
		arg.GoalID,
		arg.TaskID,
		arg.ScopeKey,
		arg.Kind,
		arg.SourceID,
		arg.Generation,
		arg.OwnerRole,
		arg.Instruction,
		arg.OpenedAt,
	)
	return err
}

const listOpenOrchestrationBlockers = `-- name: ListOpenOrchestrationBlockers :many
SELECT blocker_id, project_id, goal_id, task_id, scope_key, kind, source_id,
       generation, owner_role, instruction, opened_at, resolved_at
FROM orchestration_blockers
WHERE project_id = ? AND resolved_at IS NULL
ORDER BY opened_at, blocker_id
`

func (q *Queries) ListOpenOrchestrationBlockers(ctx context.Context, projectID int64) ([]OrchestrationBlocker, error) {
	rows, err := q.db.QueryContext(ctx, listOpenOrchestrationBlockers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestrationBlocker
	for rows.Next() {
		var i OrchestrationBlocker
		if err := rows.Scan(
			&i.BlockerID,
			&i.ProjectID,
			&i.GoalID,
			&i.TaskID,
			&i.ScopeKey,
			&i.Kind,
			&i.SourceID,
			&i.Generation,
			&i.OwnerRole,
			&i.Instruction,
			&i.OpenedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrchestrationBlockers = `-- name: ListOrchestrationBlockers :many
SELECT blocker_id, project_id, goal_id, task_id, scope_key, kind, source_id,
       generation, owner_role, instruction, opened_at, resolved_at
FROM orchestration_blockers
WHERE project_id = ?
ORDER BY opened_at, blocker_id
`

func (q *Queries) ListOrchestrationBlockers(ctx context.Context, projectID int64) ([]OrchestrationBlocker, error) {
	rows, err := q.db.QueryContext(ctx, listOrchestrationBlockers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestrationBlocker
	for rows.Next() {
		var i OrchestrationBlocker
		if err := rows.Scan(
			&i.BlockerID,
			&i.ProjectID,
			&i.GoalID,
			&i.TaskID,
			&i.ScopeKey,
			&i.Kind,
			&i.SourceID,
			&i.Generation,
			&i.OwnerRole,
			&i.Instruction,
			&i.OpenedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveHumanDecisionBlocker = `-- name: ResolveHumanDecisionBlocker :execresult
UPDATE orchestration_blockers
SET resolved_at = ?
WHERE kind = 'human_decision' AND source_id = ? AND resolved_at IS NULL
`

type ResolveHumanDecisionBlockerParams struct {
	ResolvedAt sql.NullString
	SourceID   string
}

func (q *Queries) ResolveHumanDecisionBlocker(ctx context.Context, arg ResolveHumanDecisionBlockerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, resolveHumanDecisionBlocker, arg.ResolvedAt, arg.SourceID)
}

const resolveOrchestrationBlocker = `-- name: ResolveOrchestrationBlocker :execresult
UPDATE orchestration_blockers
SET resolved_at = ?
WHERE blocker_id = ? AND resolved_at IS NULL
`

type ResolveOrchestrationBlockerParams struct {
	ResolvedAt sql.NullString
	BlockerID  string
}

func (q *Queries) ResolveOrchestrationBlocker(ctx context.Context, arg ResolveOrchestrationBlockerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, resolveOrchestrationBlocker, arg.ResolvedAt, arg.BlockerID)
}

const updateOrchestrationBlocker = `-- name: UpdateOrchestrationBlocker :exec
UPDATE orchestration_blockers
SET project_id = ?, goal_id = ?, task_id = ?, scope_key = ?, owner_role = ?,
    instruction = ?
WHERE kind = ? AND source_id = ? AND generation = ? AND resolved_at IS NULL
`

type UpdateOrchestrationBlockerParams struct {
	ProjectID   int64
	GoalID      sql.NullInt64
	TaskID      sql.NullInt64
	ScopeKey    string
	OwnerRole   string
	Instruction string
	Kind        string
	SourceID    string
	Generation  string
}

func (q *Queries) UpdateOrchestrationBlocker(ctx context.Context, arg UpdateOrchestrationBlockerParams) error {
	_, err := q.db.ExecContext(ctx, updateOrchestrationBlocker,
		arg.ProjectID,
		arg.GoalID,
		arg.TaskID,
		arg.ScopeKey,
		arg.OwnerRole,
		arg.Instruction,
		arg.Kind,
		arg.SourceID,
		arg.Generation,
	)
	return err
}
