// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orchestration_delivery.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const acceptOrchestrationDelivery = `-- name: AcceptOrchestrationDelivery :execresult
UPDATE orchestration_delivery_receipts
SET status = 'accepted', updated_at = ?
WHERE orchestration_delivery_receipts.scope_key = ? AND orchestration_delivery_receipts.delivery_key = ? AND orchestration_delivery_receipts.generation = ?
  AND orchestration_delivery_receipts.status = 'reserved'
  AND orchestration_delivery_receipts.holder_monitor_id = ? AND orchestration_delivery_receipts.fencing_token = ?
  AND EXISTS (
      SELECT 1
      FROM orchestration_delivery_leases
      WHERE orchestration_delivery_leases.scope_key = ? AND orchestration_delivery_leases.target_role = ?
        AND orchestration_delivery_leases.holder_monitor_id = ? AND orchestration_delivery_leases.fencing_token = ? AND orchestration_delivery_leases.expires_at > ?
  )
`

type AcceptOrchestrationDeliveryParams struct {
	UpdatedAt         string
	ScopeKey          string
	DeliveryKey       string
	Generation        string
	HolderMonitorID   string
	FencingToken      int64
	ScopeKey_2        string
	TargetRole        string
	HolderMonitorID_2 string
	FencingToken_2    int64
	ExpiresAt         string
}

func (q *Queries) AcceptOrchestrationDelivery(ctx context.Context, arg AcceptOrchestrationDeliveryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, acceptOrchestrationDelivery,
		arg.UpdatedAt,
		arg.ScopeKey,
		arg.DeliveryKey,
		arg.Generation,
		arg.HolderMonitorID,
		arg.FencingToken,
		arg.ScopeKey_2,
		arg.TargetRole,
		arg.HolderMonitorID_2,
		arg.FencingToken_2,
		arg.ExpiresAt,
	)
}

const acquireOrchestrationDeliveryLease = `-- name: AcquireOrchestrationDeliveryLease :execresult
INSERT INTO orchestration_delivery_leases (
    scope_key, target_role, holder_monitor_id, fencing_token, expires_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(scope_key, target_role) DO UPDATE SET
    holder_monitor_id = excluded.holder_monitor_id,
    fencing_token = orchestration_delivery_leases.fencing_token + 1,
    expires_at = excluded.expires_at,
    updated_at = excluded.updated_at
WHERE orchestration_delivery_leases.expires_at <= excluded.updated_at
`

type AcquireOrchestrationDeliveryLeaseParams struct {
	ScopeKey        string
	TargetRole      string
	HolderMonitorID string
	FencingToken    int64
	ExpiresAt       string
	UpdatedAt       string
}

func (q *Queries) AcquireOrchestrationDeliveryLease(ctx context.Context, arg AcquireOrchestrationDeliveryLeaseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, acquireOrchestrationDeliveryLease,
		arg.ScopeKey,
		arg.TargetRole,
		arg.HolderMonitorID,
		arg.FencingToken,
		arg.ExpiresAt,
		arg.UpdatedAt,
	)
}

const getOrchestrationDeliveryLease = `-- name: GetOrchestrationDeliveryLease :one
SELECT scope_key, target_role, holder_monitor_id, fencing_token, expires_at, updated_at
FROM orchestration_delivery_leases
WHERE scope_key = ? AND target_role = ?
`

type GetOrchestrationDeliveryLeaseParams struct {
	ScopeKey   string
	TargetRole string
}

func (q *Queries) GetOrchestrationDeliveryLease(ctx context.Context, arg GetOrchestrationDeliveryLeaseParams) (OrchestrationDeliveryLease, error) {
	row := q.db.QueryRowContext(ctx, getOrchestrationDeliveryLease, arg.ScopeKey, arg.TargetRole)
	var i OrchestrationDeliveryLease
	err := row.Scan(
		&i.ScopeKey,
		&i.TargetRole,
		&i.HolderMonitorID,
		&i.FencingToken,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrchestrationDeliveryMonitorHealth = `-- name: GetOrchestrationDeliveryMonitorHealth :one
SELECT monitor_id, agent_key, scope_key, agent_session_id, cwd, role, project_id, goal_id, task_id, pid,
       process_started_at, state, reason, transitioned_at, last_seen_at, stopped_at
FROM monitor_health
WHERE monitor_id = ?
`

type GetOrchestrationDeliveryMonitorHealthRow struct {
	MonitorID        string
	AgentKey         string
	ScopeKey         string
	AgentSessionID   int64
	Cwd              string
	Role             string
	ProjectID        int64
	GoalID           sql.NullInt64
	TaskID           sql.NullInt64
	Pid              int64
	ProcessStartedAt string
	State            string
	Reason           string
	TransitionedAt   string
	LastSeenAt       string
	StoppedAt        sql.NullString
}

func (q *Queries) GetOrchestrationDeliveryMonitorHealth(ctx context.Context, monitorID string) (GetOrchestrationDeliveryMonitorHealthRow, error) {
	row := q.db.QueryRowContext(ctx, getOrchestrationDeliveryMonitorHealth, monitorID)
	var i GetOrchestrationDeliveryMonitorHealthRow
	err := row.Scan(
		&i.MonitorID,
		&i.AgentKey,
		&i.ScopeKey,
		&i.AgentSessionID,
		&i.Cwd,
		&i.Role,
		&i.ProjectID,
		&i.GoalID,
		&i.TaskID,
		&i.Pid,
		&i.ProcessStartedAt,
		&i.State,
		&i.Reason,
		&i.TransitionedAt,
		&i.LastSeenAt,
		&i.StoppedAt,
	)
	return i, err
}

const getOrchestrationDeliveryReceipt = `-- name: GetOrchestrationDeliveryReceipt :one
SELECT scope_key, delivery_key, generation, target_role, holder_monitor_id,
       fencing_token, status, created_at, updated_at
FROM orchestration_delivery_receipts
WHERE scope_key = ? AND delivery_key = ? AND generation = ?
`

type GetOrchestrationDeliveryReceiptParams struct {
	ScopeKey    string
	DeliveryKey string
	Generation  string
}

func (q *Queries) GetOrchestrationDeliveryReceipt(ctx context.Context, arg GetOrchestrationDeliveryReceiptParams) (OrchestrationDeliveryReceipt, error) {
	row := q.db.QueryRowContext(ctx, getOrchestrationDeliveryReceipt, arg.ScopeKey, arg.DeliveryKey, arg.Generation)
	var i OrchestrationDeliveryReceipt
	err := row.Scan(
		&i.ScopeKey,
		&i.DeliveryKey,
		&i.Generation,
		&i.TargetRole,
		&i.HolderMonitorID,
		&i.FencingToken,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrchestrationDeliveryScope = `-- name: GetOrchestrationDeliveryScope :one
SELECT scope_key, project_id, goal_id, task_id, role, agent_session_id, agent_key,
       source_generation, active, created_at, updated_at
FROM orchestration_scope
WHERE scope_key = ?
`

func (q *Queries) GetOrchestrationDeliveryScope(ctx context.Context, scopeKey string) (OrchestrationScope, error) {
	row := q.db.QueryRowContext(ctx, getOrchestrationDeliveryScope, scopeKey)
	var i OrchestrationScope
	err := row.Scan(
		&i.ScopeKey,
		&i.ProjectID,
		&i.GoalID,
		&i.TaskID,
		&i.Role,
		&i.AgentSessionID,
		&i.AgentKey,
		&i.SourceGeneration,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrchestrationDeliveryUnknown = `-- name: MarkOrchestrationDeliveryUnknown :execresult
UPDATE orchestration_delivery_receipts
SET status = 'unknown', updated_at = ?
WHERE orchestration_delivery_receipts.scope_key = ? AND orchestration_delivery_receipts.delivery_key = ? AND orchestration_delivery_receipts.generation = ?
  AND orchestration_delivery_receipts.status = 'reserved'
  AND orchestration_delivery_receipts.holder_monitor_id = ? AND orchestration_delivery_receipts.fencing_token = ?
  AND EXISTS (
      SELECT 1
      FROM orchestration_delivery_leases
      WHERE orchestration_delivery_leases.scope_key = ? AND orchestration_delivery_leases.target_role = ?
        AND orchestration_delivery_leases.holder_monitor_id = ? AND orchestration_delivery_leases.fencing_token = ? AND orchestration_delivery_leases.expires_at > ?
  )
`

type MarkOrchestrationDeliveryUnknownParams struct {
	UpdatedAt         string
	ScopeKey          string
	DeliveryKey       string
	Generation        string
	HolderMonitorID   string
	FencingToken      int64
	ScopeKey_2        string
	TargetRole        string
	HolderMonitorID_2 string
	FencingToken_2    int64
	ExpiresAt         string
}

func (q *Queries) MarkOrchestrationDeliveryUnknown(ctx context.Context, arg MarkOrchestrationDeliveryUnknownParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markOrchestrationDeliveryUnknown,
		arg.UpdatedAt,
		arg.ScopeKey,
		arg.DeliveryKey,
		arg.Generation,
		arg.HolderMonitorID,
		arg.FencingToken,
		arg.ScopeKey_2,
		arg.TargetRole,
		arg.HolderMonitorID_2,
		arg.FencingToken_2,
		arg.ExpiresAt,
	)
}

const releaseOrchestrationDelivery = `-- name: ReleaseOrchestrationDelivery :execresult
DELETE FROM orchestration_delivery_receipts
WHERE orchestration_delivery_receipts.scope_key = ? AND orchestration_delivery_receipts.delivery_key = ? AND orchestration_delivery_receipts.generation = ?
  AND orchestration_delivery_receipts.status = 'reserved'
  AND orchestration_delivery_receipts.holder_monitor_id = ? AND orchestration_delivery_receipts.fencing_token = ?
  AND EXISTS (
      SELECT 1
      FROM orchestration_delivery_leases
      WHERE orchestration_delivery_leases.scope_key = ? AND orchestration_delivery_leases.target_role = ?
        AND orchestration_delivery_leases.holder_monitor_id = ? AND orchestration_delivery_leases.fencing_token = ? AND orchestration_delivery_leases.expires_at > ?
  )
`

type ReleaseOrchestrationDeliveryParams struct {
	ScopeKey          string
	DeliveryKey       string
	Generation        string
	HolderMonitorID   string
	FencingToken      int64
	ScopeKey_2        string
	TargetRole        string
	HolderMonitorID_2 string
	FencingToken_2    int64
	ExpiresAt         string
}

func (q *Queries) ReleaseOrchestrationDelivery(ctx context.Context, arg ReleaseOrchestrationDeliveryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, releaseOrchestrationDelivery,
		arg.ScopeKey,
		arg.DeliveryKey,
		arg.Generation,
		arg.HolderMonitorID,
		arg.FencingToken,
		arg.ScopeKey_2,
		arg.TargetRole,
		arg.HolderMonitorID_2,
		arg.FencingToken_2,
		arg.ExpiresAt,
	)
}

const renewOrchestrationDeliveryLease = `-- name: RenewOrchestrationDeliveryLease :execresult
UPDATE orchestration_delivery_leases
SET expires_at = ?, updated_at = ?
WHERE scope_key = ? AND target_role = ? AND holder_monitor_id = ? AND expires_at > ?
`

type RenewOrchestrationDeliveryLeaseParams struct {
	ExpiresAt       string
	UpdatedAt       string
	ScopeKey        string
	TargetRole      string
	HolderMonitorID string
	ExpiresAt_2     string
}

func (q *Queries) RenewOrchestrationDeliveryLease(ctx context.Context, arg RenewOrchestrationDeliveryLeaseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, renewOrchestrationDeliveryLease,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ScopeKey,
		arg.TargetRole,
		arg.HolderMonitorID,
		arg.ExpiresAt_2,
	)
}

const reserveOrchestrationDelivery = `-- name: ReserveOrchestrationDelivery :execresult
INSERT INTO orchestration_delivery_receipts (
    scope_key, delivery_key, generation, target_role, holder_monitor_id,
    fencing_token, status, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, 'reserved', ?, ?)
ON CONFLICT(scope_key, delivery_key, generation) DO UPDATE SET
    target_role = excluded.target_role,
    holder_monitor_id = excluded.holder_monitor_id,
    fencing_token = excluded.fencing_token,
    status = 'reserved',
    updated_at = excluded.updated_at
WHERE orchestration_delivery_receipts.status = 'reserved'
  AND orchestration_delivery_receipts.fencing_token < excluded.fencing_token
`

type ReserveOrchestrationDeliveryParams struct {
	ScopeKey        string
	DeliveryKey     string
	Generation      string
	TargetRole      string
	HolderMonitorID string
	FencingToken    int64
	CreatedAt       string
	UpdatedAt       string
}

func (q *Queries) ReserveOrchestrationDelivery(ctx context.Context, arg ReserveOrchestrationDeliveryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reserveOrchestrationDelivery,
		arg.ScopeKey,
		arg.DeliveryKey,
		arg.Generation,
		arg.TargetRole,
		arg.HolderMonitorID,
		arg.FencingToken,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}
