// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orchestration_review_work.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getNextTodoTaskID = `-- name: GetNextTodoTaskID :one
SELECT id
FROM tasks
WHERE goal_id = ? AND status = 'todo'
ORDER BY sort_order, id
LIMIT 1
`

func (q *Queries) GetNextTodoTaskID(ctx context.Context, goalID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextTodoTaskID, goalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOpenGoalHandoffIDForReceiver = `-- name: GetOpenGoalHandoffIDForReceiver :one
SELECT id
FROM goal_handoffs
WHERE goal_id = ? AND received_by = ? AND completed_report_at IS NULL
ORDER BY received_at DESC, id DESC
LIMIT 1
`

type GetOpenGoalHandoffIDForReceiverParams struct {
	GoalID     int64
	ReceivedBy sql.NullInt64
}

func (q *Queries) GetOpenGoalHandoffIDForReceiver(ctx context.Context, arg GetOpenGoalHandoffIDForReceiverParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getOpenGoalHandoffIDForReceiver, arg.GoalID, arg.ReceivedBy)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getOrchestrationReviewWorkReviewerScopeKey = `-- name: GetOrchestrationReviewWorkReviewerScopeKey :one
SELECT reviewer_scope_key
FROM orchestration_review_work
WHERE kind = ? AND handoff_id = ? AND review_requested_generation = ?
`

type GetOrchestrationReviewWorkReviewerScopeKeyParams struct {
	Kind                      string
	HandoffID                 string
	ReviewRequestedGeneration string
}

func (q *Queries) GetOrchestrationReviewWorkReviewerScopeKey(ctx context.Context, arg GetOrchestrationReviewWorkReviewerScopeKeyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrchestrationReviewWorkReviewerScopeKey, arg.Kind, arg.HandoffID, arg.ReviewRequestedGeneration)
	var reviewer_scope_key string
	err := row.Scan(&reviewer_scope_key)
	return reviewer_scope_key, err
}

const insertOrchestrationReviewWork = `-- name: InsertOrchestrationReviewWork :exec
INSERT INTO orchestration_review_work (
    review_work_id, project_id, goal_id, task_id, kind, handoff_id,
    requester_session_id, requester_scope_key, expected_reviewer_role,
    reviewer_scope_key, reviewer_session_id, state,
    review_requested_generation, review_received_generation,
    settlement_generation, active, action_role, action_scope_key,
    action_task_id, action_instruction, opened_at, updated_at, resolved_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NULL, 'requested', ?, NULL,
        NULL, 1, NULL, NULL, NULL, NULL, ?, ?, NULL)
`

type InsertOrchestrationReviewWorkParams struct {
	ReviewWorkID              string
	ProjectID                 int64
	GoalID                    int64
	TaskID                    sql.NullInt64
	Kind                      string
	HandoffID                 string
	RequesterSessionID        int64
	RequesterScopeKey         string
	ExpectedReviewerRole      string
	ReviewerScopeKey          string
	ReviewRequestedGeneration string
	OpenedAt                  string
	UpdatedAt                 string
}

func (q *Queries) InsertOrchestrationReviewWork(ctx context.Context, arg InsertOrchestrationReviewWorkParams) error {
	_, err := q.db.ExecContext(ctx, insertOrchestrationReviewWork,
		arg.ReviewWorkID,
		arg.ProjectID,
		arg.GoalID,
		arg.TaskID,
		arg.Kind,
		arg.HandoffID,
		arg.RequesterSessionID,
		arg.RequesterScopeKey,
		arg.ExpectedReviewerRole,
		arg.ReviewerScopeKey,
		arg.ReviewRequestedGeneration,
		arg.OpenedAt,
		arg.UpdatedAt,
	)
	return err
}

const listOrchestrationReviewWork = `-- name: ListOrchestrationReviewWork :many
SELECT review_work_id, project_id, goal_id, task_id, kind, handoff_id,
       requester_session_id, requester_scope_key, expected_reviewer_role,
       reviewer_scope_key, reviewer_session_id, state,
       review_requested_generation, review_received_generation,
       settlement_generation, active, action_role, action_scope_key,
       action_task_id, action_instruction, opened_at, updated_at, resolved_at
FROM orchestration_review_work
WHERE project_id = ?
ORDER BY opened_at, review_work_id
`

func (q *Queries) ListOrchestrationReviewWork(ctx context.Context, projectID int64) ([]OrchestrationReviewWork, error) {
	rows, err := q.db.QueryContext(ctx, listOrchestrationReviewWork, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestrationReviewWork
	for rows.Next() {
		var i OrchestrationReviewWork
		if err := rows.Scan(
			&i.ReviewWorkID,
			&i.ProjectID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.HandoffID,
			&i.RequesterSessionID,
			&i.RequesterScopeKey,
			&i.ExpectedReviewerRole,
			&i.ReviewerScopeKey,
			&i.ReviewerSessionID,
			&i.State,
			&i.ReviewRequestedGeneration,
			&i.ReviewReceivedGeneration,
			&i.SettlementGeneration,
			&i.Active,
			&i.ActionRole,
			&i.ActionScopeKey,
			&i.ActionTaskID,
			&i.ActionInstruction,
			&i.OpenedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOrchestrationReviewWork = `-- name: ListPendingOrchestrationReviewWork :many
SELECT review_work_id, project_id, goal_id, task_id, kind, handoff_id,
       requester_session_id, requester_scope_key, expected_reviewer_role,
       reviewer_scope_key, reviewer_session_id, state,
       review_requested_generation, review_received_generation,
       settlement_generation, active, action_role, action_scope_key,
       action_task_id, action_instruction, opened_at, updated_at, resolved_at
FROM orchestration_review_work AS work
WHERE work.project_id = ?
  AND (
      work.active = 1
      OR work.action_instruction IS NOT NULL
  )
  AND (
      work.state <> 'rejected'
      OR work.review_requested_generation = (
          SELECT MAX(newer.review_requested_generation)
          FROM orchestration_review_work AS newer
          WHERE newer.kind = work.kind AND newer.handoff_id = work.handoff_id
      )
  )
ORDER BY work.opened_at, work.review_work_id
`

func (q *Queries) ListPendingOrchestrationReviewWork(ctx context.Context, projectID int64) ([]OrchestrationReviewWork, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOrchestrationReviewWork, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestrationReviewWork
	for rows.Next() {
		var i OrchestrationReviewWork
		if err := rows.Scan(
			&i.ReviewWorkID,
			&i.ProjectID,
			&i.GoalID,
			&i.TaskID,
			&i.Kind,
			&i.HandoffID,
			&i.RequesterSessionID,
			&i.RequesterScopeKey,
			&i.ExpectedReviewerRole,
			&i.ReviewerScopeKey,
			&i.ReviewerSessionID,
			&i.State,
			&i.ReviewRequestedGeneration,
			&i.ReviewReceivedGeneration,
			&i.SettlementGeneration,
			&i.Active,
			&i.ActionRole,
			&i.ActionScopeKey,
			&i.ActionTaskID,
			&i.ActionInstruction,
			&i.OpenedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const receiveOrchestrationReviewWork = `-- name: ReceiveOrchestrationReviewWork :execresult
UPDATE orchestration_review_work
SET reviewer_session_id = ?,
    state = 'received',
    review_received_generation = ?,
    updated_at = ?
WHERE kind = ? AND handoff_id = ? AND review_requested_generation = ?
  AND active = 1 AND state = 'requested'
`

type ReceiveOrchestrationReviewWorkParams struct {
	ReviewerSessionID         sql.NullInt64
	ReviewReceivedGeneration  sql.NullString
	UpdatedAt                 string
	Kind                      string
	HandoffID                 string
	ReviewRequestedGeneration string
}

func (q *Queries) ReceiveOrchestrationReviewWork(ctx context.Context, arg ReceiveOrchestrationReviewWorkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, receiveOrchestrationReviewWork,
		arg.ReviewerSessionID,
		arg.ReviewReceivedGeneration,
		arg.UpdatedAt,
		arg.Kind,
		arg.HandoffID,
		arg.ReviewRequestedGeneration,
	)
}

const settleOrchestrationReviewWork = `-- name: SettleOrchestrationReviewWork :execresult
UPDATE orchestration_review_work
SET state = ?,
    settlement_generation = ?,
    active = 0,
    action_role = ?,
    action_scope_key = ?,
    action_task_id = ?,
    action_instruction = ?,
    updated_at = ?,
    resolved_at = ?
WHERE kind = ? AND handoff_id = ? AND review_requested_generation = ?
  AND active = 1
`

type SettleOrchestrationReviewWorkParams struct {
	State                     string
	SettlementGeneration      sql.NullString
	ActionRole                sql.NullString
	ActionScopeKey            sql.NullString
	ActionTaskID              sql.NullInt64
	ActionInstruction         sql.NullString
	UpdatedAt                 string
	ResolvedAt                sql.NullString
	Kind                      string
	HandoffID                 string
	ReviewRequestedGeneration string
}

func (q *Queries) SettleOrchestrationReviewWork(ctx context.Context, arg SettleOrchestrationReviewWorkParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, settleOrchestrationReviewWork,
		arg.State,
		arg.SettlementGeneration,
		arg.ActionRole,
		arg.ActionScopeKey,
		arg.ActionTaskID,
		arg.ActionInstruction,
		arg.UpdatedAt,
		arg.ResolvedAt,
		arg.Kind,
		arg.HandoffID,
		arg.ReviewRequestedGeneration,
	)
}
