// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orchestration_scope.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deactivateOrchestrationScope = `-- name: DeactivateOrchestrationScope :execresult
UPDATE orchestration_scope
SET active = 0, updated_at = ?
WHERE scope_key = ? AND active = 1
`

type DeactivateOrchestrationScopeParams struct {
	UpdatedAt string
	ScopeKey  string
}

func (q *Queries) DeactivateOrchestrationScope(ctx context.Context, arg DeactivateOrchestrationScopeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deactivateOrchestrationScope, arg.UpdatedAt, arg.ScopeKey)
}

const deactivateOrchestrationScopesForGoal = `-- name: DeactivateOrchestrationScopesForGoal :exec
UPDATE orchestration_scope
SET active = 0, updated_at = ?
WHERE goal_id = ? AND active = 1
`

type DeactivateOrchestrationScopesForGoalParams struct {
	UpdatedAt string
	GoalID    sql.NullInt64
}

func (q *Queries) DeactivateOrchestrationScopesForGoal(ctx context.Context, arg DeactivateOrchestrationScopesForGoalParams) error {
	_, err := q.db.ExecContext(ctx, deactivateOrchestrationScopesForGoal, arg.UpdatedAt, arg.GoalID)
	return err
}

const deactivateOrchestrationScopesForTask = `-- name: DeactivateOrchestrationScopesForTask :exec
UPDATE orchestration_scope
SET active = 0, updated_at = ?
WHERE task_id = ? AND active = 1
`

type DeactivateOrchestrationScopesForTaskParams struct {
	UpdatedAt string
	TaskID    sql.NullInt64
}

func (q *Queries) DeactivateOrchestrationScopesForTask(ctx context.Context, arg DeactivateOrchestrationScopesForTaskParams) error {
	_, err := q.db.ExecContext(ctx, deactivateOrchestrationScopesForTask, arg.UpdatedAt, arg.TaskID)
	return err
}

const getAgentSessionKey = `-- name: GetAgentSessionKey :one
SELECT session_key
FROM agent_sessions
WHERE id = ?
`

func (q *Queries) GetAgentSessionKey(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionKey, id)
	var session_key string
	err := row.Scan(&session_key)
	return session_key, err
}

const listActiveOrchestrationScopes = `-- name: ListActiveOrchestrationScopes :many
SELECT scope_key, project_id, goal_id, task_id, role, agent_session_id, agent_key,
       source_generation, active, created_at, updated_at
FROM orchestration_scope
WHERE project_id = ? AND active = 1
ORDER BY created_at, scope_key
`

func (q *Queries) ListActiveOrchestrationScopes(ctx context.Context, projectID int64) ([]OrchestrationScope, error) {
	rows, err := q.db.QueryContext(ctx, listActiveOrchestrationScopes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestrationScope
	for rows.Next() {
		var i OrchestrationScope
		if err := rows.Scan(
			&i.ScopeKey,
			&i.ProjectID,
			&i.GoalID,
			&i.TaskID,
			&i.Role,
			&i.AgentSessionID,
			&i.AgentKey,
			&i.SourceGeneration,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrchestrationScopes = `-- name: ListOrchestrationScopes :many
SELECT scope_key, project_id, goal_id, task_id, role, agent_session_id, agent_key,
       source_generation, active, created_at, updated_at
FROM orchestration_scope
WHERE project_id = ?
ORDER BY created_at, scope_key
`

func (q *Queries) ListOrchestrationScopes(ctx context.Context, projectID int64) ([]OrchestrationScope, error) {
	rows, err := q.db.QueryContext(ctx, listOrchestrationScopes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrchestrationScope
	for rows.Next() {
		var i OrchestrationScope
		if err := rows.Scan(
			&i.ScopeKey,
			&i.ProjectID,
			&i.GoalID,
			&i.TaskID,
			&i.Role,
			&i.AgentSessionID,
			&i.AgentKey,
			&i.SourceGeneration,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrchestrationScope = `-- name: UpsertOrchestrationScope :exec
INSERT INTO orchestration_scope (
  scope_key, project_id, goal_id, task_id, role, agent_session_id, agent_key,
  source_generation, active, created_at, updated_at
)
VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6,
  ?7, ?8, 1,
  ?9, ?10
)
ON CONFLICT(scope_key) DO UPDATE SET
  project_id = excluded.project_id,
  goal_id = excluded.goal_id,
  task_id = excluded.task_id,
  role = excluded.role,
  agent_session_id = excluded.agent_session_id,
  agent_key = excluded.agent_key,
  source_generation = excluded.source_generation,
  active = 1,
  updated_at = excluded.updated_at
`

type UpsertOrchestrationScopeParams struct {
	ScopeKey         string
	ProjectID        int64
	GoalID           sql.NullInt64
	TaskID           sql.NullInt64
	Role             string
	AgentSessionID   int64
	AgentKey         string
	SourceGeneration string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) UpsertOrchestrationScope(ctx context.Context, arg UpsertOrchestrationScopeParams) error {
	_, err := q.db.ExecContext(ctx, upsertOrchestrationScope,
		arg.ScopeKey,
		arg.ProjectID,
		arg.GoalID,
		arg.TaskID,
		arg.Role,
		arg.AgentSessionID,
		arg.AgentKey,
		arg.SourceGeneration,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
