// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package sqlcgen

import (
	"context"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, root_path, created_at)
VALUES (?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID        string
	Name      string
	RootPath  string
	CreatedAt string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.RootPath,
		arg.CreatedAt,
	)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, root_path, created_at
FROM projects
ORDER BY created_at
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RootPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveProject = `-- name: ResolveProject :one
SELECT id, name, root_path, created_at
FROM projects
WHERE ? = root_path OR ? LIKE root_path || '/%'
ORDER BY LENGTH(root_path) DESC
LIMIT 1
`

type ResolveProjectParams struct {
	RootPath   string
	RootPath_2 string
}

func (q *Queries) ResolveProject(ctx context.Context, arg ResolveProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, resolveProject, arg.RootPath, arg.RootPath_2)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.CreatedAt,
	)
	return i, err
}
