// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const claimProject = `-- name: ClaimProject :execresult
UPDATE projects
SET claimed_by = ?, claimed_at = ?
WHERE id = ?
`

type ClaimProjectParams struct {
	ClaimedBy string
	ClaimedAt sql.NullString
	ID        string
}

func (q *Queries) ClaimProject(ctx context.Context, arg ClaimProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimProject, arg.ClaimedBy, arg.ClaimedAt, arg.ID)
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, root_path, created_at)
VALUES (?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID        string
	Name      string
	RootPath  string
	CreatedAt string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.RootPath,
		arg.CreatedAt,
	)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, root_path, created_at, claimed_by, claimed_at
FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.CreatedAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, root_path, created_at, claimed_by, claimed_at
FROM projects
ORDER BY created_at
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RootPath,
			&i.CreatedAt,
			&i.ClaimedBy,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseProject = `-- name: ReleaseProject :execresult
UPDATE projects
SET claimed_by = '', claimed_at = NULL
WHERE id = ?
`

func (q *Queries) ReleaseProject(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, releaseProject, id)
}

const resolveProject = `-- name: ResolveProject :one
SELECT id, name, root_path, created_at, claimed_by, claimed_at
FROM projects
WHERE ? = root_path OR ? LIKE root_path || '/%'
ORDER BY LENGTH(root_path) DESC
LIMIT 1
`

type ResolveProjectParams struct {
	RootPath   string
	RootPath_2 string
}

func (q *Queries) ResolveProject(ctx context.Context, arg ResolveProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, resolveProject, arg.RootPath, arg.RootPath_2)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RootPath,
		&i.CreatedAt,
		&i.ClaimedBy,
		&i.ClaimedAt,
	)
	return i, err
}
