// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_exchange.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPlanHandoffEntry = `-- name: CreatePlanHandoffEntry :one
INSERT INTO plan_handoff_entries (
  handoff_id, kind, body, author_session_id, created_at
)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreatePlanHandoffEntryParams struct {
	HandoffID       string
	Kind            string
	Body            string
	AuthorSessionID sql.NullInt64
	CreatedAt       string
}

func (q *Queries) CreatePlanHandoffEntry(ctx context.Context, arg CreatePlanHandoffEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPlanHandoffEntry,
		arg.HandoffID,
		arg.Kind,
		arg.Body,
		arg.AuthorSessionID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listGoalReviewDecisions = `-- name: ListGoalReviewDecisions :many
SELECT id, status, answer_label, answer_text, answered_at, created_at, agent_session_id
FROM decisions
WHERE goal_id = ? AND kind = 'goal_review'
  AND (answer_label = 'reject' OR status = 'withdrawn')
ORDER BY id
`

type ListGoalReviewDecisionsRow struct {
	ID             int64
	Status         string
	AnswerLabel    string
	AnswerText     string
	AnsweredAt     sql.NullString
	CreatedAt      string
	AgentSessionID int64
}

func (q *Queries) ListGoalReviewDecisions(ctx context.Context, goalID int64) ([]ListGoalReviewDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoalReviewDecisions, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalReviewDecisionsRow
	for rows.Next() {
		var i ListGoalReviewDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AnswerLabel,
			&i.AnswerText,
			&i.AnsweredAt,
			&i.CreatedAt,
			&i.AgentSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalReviewExchangeEntries = `-- name: ListGoalReviewExchangeEntries :many
SELECT e.id, e.handoff_id, e.kind, e.body, e.author_session_id, e.created_at
FROM goal_handoff_entries AS e
JOIN goal_handoffs AS h ON h.id = e.handoff_id
WHERE h.goal_id = ? AND e.kind IN ('review_requested', 'review_rejected')
ORDER BY e.created_at, e.id
`

type ListGoalReviewExchangeEntriesRow struct {
	ID              int64
	HandoffID       string
	Kind            string
	Body            string
	AuthorSessionID sql.NullInt64
	CreatedAt       string
}

func (q *Queries) ListGoalReviewExchangeEntries(ctx context.Context, goalID int64) ([]ListGoalReviewExchangeEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoalReviewExchangeEntries, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalReviewExchangeEntriesRow
	for rows.Next() {
		var i ListGoalReviewExchangeEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.HandoffID,
			&i.Kind,
			&i.Body,
			&i.AuthorSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalReviewGaps = `-- name: ListGoalReviewGaps :many
SELECT g.handoff_id,
       (SELECT MIN(e.created_at) FROM goal_handoff_entries AS e
         WHERE e.handoff_id = g.handoff_id
           AND e.kind IN ('review_requested', 'review_received', 'review_rejected')) AS before_at
FROM handoff_history_gaps AS g
JOIN goal_handoffs AS h ON h.id = g.handoff_id
WHERE g.scope = 'goal' AND h.goal_id = ?
ORDER BY g.handoff_id
`

type ListGoalReviewGapsRow struct {
	HandoffID string
	BeforeAt  interface{}
}

func (q *Queries) ListGoalReviewGaps(ctx context.Context, goalID int64) ([]ListGoalReviewGapsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGoalReviewGaps, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalReviewGapsRow
	for rows.Next() {
		var i ListGoalReviewGapsRow
		if err := rows.Scan(&i.HandoffID, &i.BeforeAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanReviewExchangeEntries = `-- name: ListPlanReviewExchangeEntries :many
SELECT e.id, e.handoff_id, e.kind, e.body, e.author_session_id, e.created_at
FROM plan_handoff_entries AS e
JOIN plan_handoffs AS h ON h.id = e.handoff_id
WHERE h.goal_id = ?
ORDER BY e.created_at, e.id
`

func (q *Queries) ListPlanReviewExchangeEntries(ctx context.Context, goalID int64) ([]PlanHandoffEntry, error) {
	rows, err := q.db.QueryContext(ctx, listPlanReviewExchangeEntries, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanHandoffEntry
	for rows.Next() {
		var i PlanHandoffEntry
		if err := rows.Scan(
			&i.ID,
			&i.HandoffID,
			&i.Kind,
			&i.Body,
			&i.AuthorSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanReviewGaps = `-- name: ListPlanReviewGaps :many
SELECT g.handoff_id,
       (SELECT MIN(e.created_at) FROM plan_handoff_entries AS e
         WHERE e.handoff_id = g.handoff_id) AS before_at
FROM handoff_history_gaps AS g
JOIN plan_handoffs AS h ON h.id = g.handoff_id
WHERE g.scope = 'plan' AND h.goal_id = ?
ORDER BY g.handoff_id
`

type ListPlanReviewGapsRow struct {
	HandoffID string
	BeforeAt  interface{}
}

func (q *Queries) ListPlanReviewGaps(ctx context.Context, goalID int64) ([]ListPlanReviewGapsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlanReviewGaps, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlanReviewGapsRow
	for rows.Next() {
		var i ListPlanReviewGapsRow
		if err := rows.Scan(&i.HandoffID, &i.BeforeAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskReviewExchangeEntries = `-- name: ListTaskReviewExchangeEntries :many
SELECT h.task_id, e.id, e.handoff_id, e.kind, e.body, e.author_session_id, e.created_at
FROM task_handoff_entries AS e
JOIN task_handoffs AS h ON h.id = e.handoff_id
JOIN tasks AS t ON t.id = h.task_id
WHERE t.goal_id = ?1
  AND (?2 = 0 OR h.task_id = ?2)
  AND e.kind IN ('review_requested', 'review_rejected')
ORDER BY e.created_at, e.id
`

type ListTaskReviewExchangeEntriesParams struct {
	GoalID int64
	TaskID interface{}
}

type ListTaskReviewExchangeEntriesRow struct {
	TaskID          int64
	ID              int64
	HandoffID       string
	Kind            string
	Body            string
	AuthorSessionID sql.NullInt64
	CreatedAt       string
}

func (q *Queries) ListTaskReviewExchangeEntries(ctx context.Context, arg ListTaskReviewExchangeEntriesParams) ([]ListTaskReviewExchangeEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskReviewExchangeEntries, arg.GoalID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskReviewExchangeEntriesRow
	for rows.Next() {
		var i ListTaskReviewExchangeEntriesRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ID,
			&i.HandoffID,
			&i.Kind,
			&i.Body,
			&i.AuthorSessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskReviewGaps = `-- name: ListTaskReviewGaps :many
SELECT g.handoff_id, h.task_id,
       (SELECT MIN(e.created_at) FROM task_handoff_entries AS e
         WHERE e.handoff_id = g.handoff_id
           AND e.kind IN ('review_requested', 'review_received', 'review_rejected')) AS before_at
FROM handoff_history_gaps AS g
JOIN task_handoffs AS h ON h.id = g.handoff_id
JOIN tasks AS t ON t.id = h.task_id
WHERE g.scope = 'task' AND t.goal_id = ?1
  AND (?2 = 0 OR h.task_id = ?2)
ORDER BY g.handoff_id
`

type ListTaskReviewGapsParams struct {
	GoalID int64
	TaskID interface{}
}

type ListTaskReviewGapsRow struct {
	HandoffID string
	TaskID    int64
	BeforeAt  interface{}
}

func (q *Queries) ListTaskReviewGaps(ctx context.Context, arg ListTaskReviewGapsParams) ([]ListTaskReviewGapsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskReviewGaps, arg.GoalID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskReviewGapsRow
	for rows.Next() {
		var i ListTaskReviewGapsRow
		if err := rows.Scan(&i.HandoffID, &i.TaskID, &i.BeforeAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
