// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const completeGoalHandoff = `-- name: CompleteGoalHandoff :exec
INSERT INTO goal_handoffs (id, goal_id, completed_report_at, complete_report)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  completed_report_at = COALESCE(goal_handoffs.completed_report_at, excluded.completed_report_at),
  complete_report = COALESCE(goal_handoffs.complete_report, excluded.complete_report)
`

type CompleteGoalHandoffParams struct {
	ID                string
	GoalID            string
	CompletedReportAt sql.NullString
	CompleteReport    sql.NullString
}

func (q *Queries) CompleteGoalHandoff(ctx context.Context, arg CompleteGoalHandoffParams) error {
	_, err := q.db.ExecContext(ctx, completeGoalHandoff,
		arg.ID,
		arg.GoalID,
		arg.CompletedReportAt,
		arg.CompleteReport,
	)
	return err
}

const completeTaskHandoff = `-- name: CompleteTaskHandoff :exec
INSERT INTO task_handoffs (id, task_id, completed_report_at, complete_report)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  completed_report_at = COALESCE(task_handoffs.completed_report_at, excluded.completed_report_at),
  complete_report = COALESCE(task_handoffs.complete_report, excluded.complete_report)
`

type CompleteTaskHandoffParams struct {
	ID                string
	TaskID            string
	CompletedReportAt sql.NullString
	CompleteReport    sql.NullString
}

func (q *Queries) CompleteTaskHandoff(ctx context.Context, arg CompleteTaskHandoffParams) error {
	_, err := q.db.ExecContext(ctx, completeTaskHandoff,
		arg.ID,
		arg.TaskID,
		arg.CompletedReportAt,
		arg.CompleteReport,
	)
	return err
}

const countOpenDecisionsForTask = `-- name: CountOpenDecisionsForTask :one
SELECT COUNT(*)
FROM decisions
WHERE task_id = ? AND status = 'open'
`

func (q *Queries) CountOpenDecisionsForTask(ctx context.Context, taskID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenDecisionsForTask, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (
  id, goal_id, title, description, status, agent, files, sort_order, declare_key,
  snoozed_until, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(goal_id, declare_key) DO NOTHING
`

type CreateTaskParams struct {
	ID           string
	GoalID       string
	Title        string
	Description  string
	Status       string
	Agent        string
	Files        string
	SortOrder    int64
	DeclareKey   string
	SnoozedUntil sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.GoalID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Agent,
		arg.Files,
		arg.SortOrder,
		arg.DeclareKey,
		arg.SnoozedUntil,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteExpiredAgentSessions = `-- name: DeleteExpiredAgentSessions :exec
DELETE FROM agent_sessions
WHERE registered_at < ?
`

func (q *Queries) DeleteExpiredAgentSessions(ctx context.Context, registeredAt string) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAgentSessions, registeredAt)
	return err
}

const deleteExpiredAgentSessionsExcept = `-- name: DeleteExpiredAgentSessionsExcept :exec
DELETE FROM agent_sessions
WHERE id <> ? AND registered_at < ?
`

type DeleteExpiredAgentSessionsExceptParams struct {
	ID           string
	RegisteredAt string
}

func (q *Queries) DeleteExpiredAgentSessionsExcept(ctx context.Context, arg DeleteExpiredAgentSessionsExceptParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAgentSessionsExcept, arg.ID, arg.RegisteredAt)
	return err
}

const dropOpenTasksForGoal = `-- name: DropOpenTasksForGoal :execresult
UPDATE tasks SET status = 'dropped', updated_at = ?
WHERE goal_id = ? AND status IN ('todo', 'doing')
`

type DropOpenTasksForGoalParams struct {
	UpdatedAt string
	GoalID    string
}

func (q *Queries) DropOpenTasksForGoal(ctx context.Context, arg DropOpenTasksForGoalParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, dropOpenTasksForGoal, arg.UpdatedAt, arg.GoalID)
}

const getAgentSessionIDByKey = `-- name: GetAgentSessionIDByKey :one
SELECT id
FROM agent_sessions
WHERE session_key = ?
`

func (q *Queries) GetAgentSessionIDByKey(ctx context.Context, sessionKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionIDByKey, sessionKey)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getAgentSessionLiveness = `-- name: GetAgentSessionLiveness :one
SELECT pid, started_at
FROM agent_sessions
WHERE id = ?
`

type GetAgentSessionLivenessRow struct {
	Pid       int64
	StartedAt string
}

func (q *Queries) GetAgentSessionLiveness(ctx context.Context, id string) (GetAgentSessionLivenessRow, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionLiveness, id)
	var i GetAgentSessionLivenessRow
	err := row.Scan(&i.Pid, &i.StartedAt)
	return i, err
}

const getAgentSessionProjectID = `-- name: GetAgentSessionProjectID :one
SELECT project_id
FROM agent_sessions
WHERE id = ?
`

func (q *Queries) GetAgentSessionProjectID(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getAgentSessionProjectID, id)
	var project_id sql.NullString
	err := row.Scan(&project_id)
	return project_id, err
}

const getGoalHandoff = `-- name: GetGoalHandoff :one
SELECT id, goal_id, requested_by, received_by,
       requested_at, received_at, completed_report_at,
       request_report, complete_report
FROM goal_handoffs
WHERE id = ?
`

func (q *Queries) GetGoalHandoff(ctx context.Context, id string) (GoalHandoff, error) {
	row := q.db.QueryRowContext(ctx, getGoalHandoff, id)
	var i GoalHandoff
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.RequestedBy,
		&i.ReceivedBy,
		&i.RequestedAt,
		&i.ReceivedAt,
		&i.CompletedReportAt,
		&i.RequestReport,
		&i.CompleteReport,
	)
	return i, err
}

const getGoalHandoffGoalID = `-- name: GetGoalHandoffGoalID :one
SELECT goal_id
FROM goal_handoffs
WHERE id = ?
`

func (q *Queries) GetGoalHandoffGoalID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGoalHandoffGoalID, id)
	var goal_id string
	err := row.Scan(&goal_id)
	return goal_id, err
}

const getLatestAgentSessionID = `-- name: GetLatestAgentSessionID :one
SELECT id
FROM agent_sessions
WHERE project_id = ?
ORDER BY registered_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentSessionID(ctx context.Context, projectID sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestAgentSessionID, projectID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getTaskForClaim = `-- name: GetTaskForClaim :one
SELECT t.goal_id, t.title, t.description, t.status, t.files,
       g.status AS goal_status
FROM tasks AS t
JOIN goals AS g ON g.id = t.goal_id
WHERE t.id = ?
`

type GetTaskForClaimRow struct {
	GoalID      string
	Title       string
	Description string
	Status      string
	Files       string
	GoalStatus  string
}

func (q *Queries) GetTaskForClaim(ctx context.Context, id string) (GetTaskForClaimRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskForClaim, id)
	var i GetTaskForClaimRow
	err := row.Scan(
		&i.GoalID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Files,
		&i.GoalStatus,
	)
	return i, err
}

const getTaskGoalID = `-- name: GetTaskGoalID :one
SELECT goal_id
FROM tasks
WHERE id = ?
`

func (q *Queries) GetTaskGoalID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskGoalID, id)
	var goal_id string
	err := row.Scan(&goal_id)
	return goal_id, err
}

const getTaskHandoff = `-- name: GetTaskHandoff :one
SELECT id, task_id, requested_by, received_by,
       requested_at, received_at, completed_report_at,
       request_report, complete_report
FROM task_handoffs
WHERE id = ?
`

func (q *Queries) GetTaskHandoff(ctx context.Context, id string) (TaskHandoff, error) {
	row := q.db.QueryRowContext(ctx, getTaskHandoff, id)
	var i TaskHandoff
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.RequestedBy,
		&i.ReceivedBy,
		&i.RequestedAt,
		&i.ReceivedAt,
		&i.CompletedReportAt,
		&i.RequestReport,
		&i.CompleteReport,
	)
	return i, err
}

const getTaskHandoffTaskID = `-- name: GetTaskHandoffTaskID :one
SELECT task_id
FROM task_handoffs
WHERE id = ?
`

func (q *Queries) GetTaskHandoffTaskID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskHandoffTaskID, id)
	var task_id string
	err := row.Scan(&task_id)
	return task_id, err
}

const getTaskProjectID = `-- name: GetTaskProjectID :one
SELECT g.project_id
FROM tasks AS t
JOIN goals AS g ON g.id = t.goal_id
WHERE t.id = ?
`

func (q *Queries) GetTaskProjectID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskProjectID, id)
	var project_id string
	err := row.Scan(&project_id)
	return project_id, err
}

const insertAgentSessionAssociation = `-- name: InsertAgentSessionAssociation :exec
INSERT INTO agent_sessions (id, project_id, registered_at)
VALUES (?, ?, ?)
`

type InsertAgentSessionAssociationParams struct {
	ID           string
	ProjectID    sql.NullString
	RegisteredAt string
}

func (q *Queries) InsertAgentSessionAssociation(ctx context.Context, arg InsertAgentSessionAssociationParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentSessionAssociation, arg.ID, arg.ProjectID, arg.RegisteredAt)
	return err
}

const linkTaskCommit = `-- name: LinkTaskCommit :exec
INSERT OR REPLACE INTO task_commits (
  task_id, sha, subject, files_changed, insertions, deletions, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type LinkTaskCommitParams struct {
	TaskID       string
	Sha          string
	Subject      string
	FilesChanged int64
	Insertions   int64
	Deletions    int64
	CreatedAt    string
}

func (q *Queries) LinkTaskCommit(ctx context.Context, arg LinkTaskCommitParams) error {
	_, err := q.db.ExecContext(ctx, linkTaskCommit,
		arg.TaskID,
		arg.Sha,
		arg.Subject,
		arg.FilesChanged,
		arg.Insertions,
		arg.Deletions,
		arg.CreatedAt,
	)
	return err
}

const listGoalHandoffs = `-- name: ListGoalHandoffs :many
SELECT id, goal_id, requested_by, received_by,
       requested_at, received_at, completed_report_at,
       request_report, complete_report
FROM goal_handoffs
WHERE goal_id = ?
ORDER BY id
`

func (q *Queries) ListGoalHandoffs(ctx context.Context, goalID string) ([]GoalHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listGoalHandoffs, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoalHandoff
	for rows.Next() {
		var i GoalHandoff
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.RequestedBy,
			&i.ReceivedBy,
			&i.RequestedAt,
			&i.ReceivedAt,
			&i.CompletedReportAt,
			&i.RequestReport,
			&i.CompleteReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenTaskHandoffsForGoal = `-- name: ListOpenTaskHandoffsForGoal :many
SELECT th.id, th.task_id, th.requested_by, th.received_by,
       th.requested_at, th.received_at, th.completed_report_at,
       th.request_report, th.complete_report
FROM task_handoffs AS th
JOIN tasks AS t ON t.id = th.task_id
WHERE t.goal_id = ?
  AND th.completed_report_at IS NULL
ORDER BY th.id
`

func (q *Queries) ListOpenTaskHandoffsForGoal(ctx context.Context, goalID string) ([]TaskHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listOpenTaskHandoffsForGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskHandoff
	for rows.Next() {
		var i TaskHandoff
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.RequestedBy,
			&i.ReceivedBy,
			&i.RequestedAt,
			&i.ReceivedAt,
			&i.CompletedReportAt,
			&i.RequestReport,
			&i.CompleteReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAlternatives = `-- name: ListTaskAlternatives :many
SELECT id, title, description, status, files
FROM tasks
WHERE goal_id = ?
  AND id <> ?
ORDER BY sort_order, id
`

type ListTaskAlternativesParams struct {
	GoalID string
	ID     string
}

type ListTaskAlternativesRow struct {
	ID          string
	Title       string
	Description string
	Status      string
	Files       string
}

func (q *Queries) ListTaskAlternatives(ctx context.Context, arg ListTaskAlternativesParams) ([]ListTaskAlternativesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAlternatives, arg.GoalID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskAlternativesRow
	for rows.Next() {
		var i ListTaskAlternativesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Files,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskCommits = `-- name: ListTaskCommits :many
SELECT sha, subject, files_changed, insertions, deletions, created_at
FROM task_commits
WHERE task_id = ?
ORDER BY created_at ASC
`

type ListTaskCommitsRow struct {
	Sha          string
	Subject      string
	FilesChanged int64
	Insertions   int64
	Deletions    int64
	CreatedAt    string
}

func (q *Queries) ListTaskCommits(ctx context.Context, taskID string) ([]ListTaskCommitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskCommits, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskCommitsRow
	for rows.Next() {
		var i ListTaskCommitsRow
		if err := rows.Scan(
			&i.Sha,
			&i.Subject,
			&i.FilesChanged,
			&i.Insertions,
			&i.Deletions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskHandoffs = `-- name: ListTaskHandoffs :many
SELECT id, task_id, requested_by, received_by,
       requested_at, received_at, completed_report_at,
       request_report, complete_report
FROM task_handoffs
WHERE task_id = ?
ORDER BY id
`

func (q *Queries) ListTaskHandoffs(ctx context.Context, taskID string) ([]TaskHandoff, error) {
	rows, err := q.db.QueryContext(ctx, listTaskHandoffs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskHandoff
	for rows.Next() {
		var i TaskHandoff
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.RequestedBy,
			&i.ReceivedBy,
			&i.RequestedAt,
			&i.ReceivedAt,
			&i.CompletedReportAt,
			&i.RequestReport,
			&i.CompleteReport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT
  id, goal_id, title, description, status, agent, files, sort_order, declare_key,
  snoozed_until, created_at, updated_at
FROM tasks
WHERE goal_id = ?
ORDER BY sort_order, id
`

func (q *Queries) ListTasks(ctx context.Context, goalID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Agent,
			&i.Files,
			&i.SortOrder,
			&i.DeclareKey,
			&i.SnoozedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTaskSortOrder = `-- name: MaxTaskSortOrder :one
SELECT CAST(COALESCE(MAX(sort_order), -1) AS INTEGER) AS sort_order
FROM tasks
WHERE goal_id = ?
`

func (q *Queries) MaxTaskSortOrder(ctx context.Context, goalID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxTaskSortOrder, goalID)
	var sort_order int64
	err := row.Scan(&sort_order)
	return sort_order, err
}

const receiveGoalHandoff = `-- name: ReceiveGoalHandoff :exec
INSERT INTO goal_handoffs (id, goal_id, received_by, received_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  received_by = COALESCE(goal_handoffs.received_by, excluded.received_by),
  received_at = COALESCE(goal_handoffs.received_at, excluded.received_at)
`

type ReceiveGoalHandoffParams struct {
	ID         string
	GoalID     string
	ReceivedBy sql.NullString
	ReceivedAt sql.NullString
}

func (q *Queries) ReceiveGoalHandoff(ctx context.Context, arg ReceiveGoalHandoffParams) error {
	_, err := q.db.ExecContext(ctx, receiveGoalHandoff,
		arg.ID,
		arg.GoalID,
		arg.ReceivedBy,
		arg.ReceivedAt,
	)
	return err
}

const receiveTaskHandoff = `-- name: ReceiveTaskHandoff :exec
INSERT INTO task_handoffs (id, task_id, received_by, received_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  received_by = COALESCE(task_handoffs.received_by, excluded.received_by),
  received_at = COALESCE(task_handoffs.received_at, excluded.received_at)
`

type ReceiveTaskHandoffParams struct {
	ID         string
	TaskID     string
	ReceivedBy sql.NullString
	ReceivedAt sql.NullString
}

func (q *Queries) ReceiveTaskHandoff(ctx context.Context, arg ReceiveTaskHandoffParams) error {
	_, err := q.db.ExecContext(ctx, receiveTaskHandoff,
		arg.ID,
		arg.TaskID,
		arg.ReceivedBy,
		arg.ReceivedAt,
	)
	return err
}

const registerAgentSession = `-- name: RegisterAgentSession :exec
INSERT OR IGNORE INTO agent_sessions (id, project_id, pid, started_at, registered_at)
VALUES (?, NULL, ?, ?, ?)
`

type RegisterAgentSessionParams struct {
	ID           string
	Pid          int64
	StartedAt    string
	RegisteredAt string
}

func (q *Queries) RegisterAgentSession(ctx context.Context, arg RegisterAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, registerAgentSession,
		arg.ID,
		arg.Pid,
		arg.StartedAt,
		arg.RegisteredAt,
	)
	return err
}

const releaseTask = `-- name: ReleaseTask :execresult
UPDATE tasks
SET status = 'todo', updated_at = ?
WHERE id = ?
`

type ReleaseTaskParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) ReleaseTask(ctx context.Context, arg ReleaseTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, releaseTask, arg.UpdatedAt, arg.ID)
}

const requestGoalHandoff = `-- name: RequestGoalHandoff :exec
INSERT INTO goal_handoffs (id, goal_id, requested_by, requested_at, request_report)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  requested_by = COALESCE(goal_handoffs.requested_by, excluded.requested_by),
  requested_at = COALESCE(goal_handoffs.requested_at, excluded.requested_at),
  request_report = COALESCE(goal_handoffs.request_report, excluded.request_report)
`

type RequestGoalHandoffParams struct {
	ID            string
	GoalID        string
	RequestedBy   sql.NullString
	RequestedAt   sql.NullString
	RequestReport sql.NullString
}

func (q *Queries) RequestGoalHandoff(ctx context.Context, arg RequestGoalHandoffParams) error {
	_, err := q.db.ExecContext(ctx, requestGoalHandoff,
		arg.ID,
		arg.GoalID,
		arg.RequestedBy,
		arg.RequestedAt,
		arg.RequestReport,
	)
	return err
}

const requestTaskHandoff = `-- name: RequestTaskHandoff :exec
INSERT INTO task_handoffs (id, task_id, requested_by, requested_at, request_report)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  requested_by = COALESCE(task_handoffs.requested_by, excluded.requested_by),
  requested_at = COALESCE(task_handoffs.requested_at, excluded.requested_at),
  request_report = COALESCE(task_handoffs.request_report, excluded.request_report)
`

type RequestTaskHandoffParams struct {
	ID            string
	TaskID        string
	RequestedBy   sql.NullString
	RequestedAt   sql.NullString
	RequestReport sql.NullString
}

func (q *Queries) RequestTaskHandoff(ctx context.Context, arg RequestTaskHandoffParams) error {
	_, err := q.db.ExecContext(ctx, requestTaskHandoff,
		arg.ID,
		arg.TaskID,
		arg.RequestedBy,
		arg.RequestedAt,
		arg.RequestReport,
	)
	return err
}

const taskExists = `-- name: TaskExists :one
SELECT id
FROM tasks
WHERE id = ?
`

func (q *Queries) TaskExists(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, taskExists, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const updateAgentSessionKey = `-- name: UpdateAgentSessionKey :exec
UPDATE agent_sessions
SET session_key = ?
WHERE id = ?
`

type UpdateAgentSessionKeyParams struct {
	SessionKey string
	ID         string
}

func (q *Queries) UpdateAgentSessionKey(ctx context.Context, arg UpdateAgentSessionKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentSessionKey, arg.SessionKey, arg.ID)
	return err
}

const updateAgentSessionProcessIdentity = `-- name: UpdateAgentSessionProcessIdentity :exec
UPDATE agent_sessions
SET pid = ?, started_at = ?, registered_at = ?
WHERE id = ?
`

type UpdateAgentSessionProcessIdentityParams struct {
	Pid          int64
	StartedAt    string
	RegisteredAt string
	ID           string
}

func (q *Queries) UpdateAgentSessionProcessIdentity(ctx context.Context, arg UpdateAgentSessionProcessIdentityParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentSessionProcessIdentity,
		arg.Pid,
		arg.StartedAt,
		arg.RegisteredAt,
		arg.ID,
	)
	return err
}

const updateAgentSessionProject = `-- name: UpdateAgentSessionProject :execresult
UPDATE agent_sessions
SET project_id = ?
WHERE id = ?
`

type UpdateAgentSessionProjectParams struct {
	ProjectID sql.NullString
	ID        string
}

func (q *Queries) UpdateAgentSessionProject(ctx context.Context, arg UpdateAgentSessionProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAgentSessionProject, arg.ProjectID, arg.ID)
}

const updateTaskSnooze = `-- name: UpdateTaskSnooze :execresult
UPDATE tasks
SET snoozed_until = ?, updated_at = ?
WHERE id = ?
`

type UpdateTaskSnoozeParams struct {
	SnoozedUntil sql.NullString
	UpdatedAt    string
	ID           string
}

func (q *Queries) UpdateTaskSnooze(ctx context.Context, arg UpdateTaskSnoozeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskSnooze, arg.SnoozedUntil, arg.UpdatedAt, arg.ID)
}

const updateTaskStatus = `-- name: UpdateTaskStatus :execresult
UPDATE tasks
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.UpdatedAt, arg.ID)
}
