// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const claimTask = `-- name: ClaimTask :execresult
UPDATE tasks
SET claimed_by = ?, claimed_at = ?, updated_at = ?
WHERE id = ? AND claimed_by = ''
`

type ClaimTaskParams struct {
	ClaimedBy string
	ClaimedAt sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, claimTask,
		arg.ClaimedBy,
		arg.ClaimedAt,
		arg.UpdatedAt,
		arg.ID,
	)
}

const countOpenDecisionsForTask = `-- name: CountOpenDecisionsForTask :one
SELECT COUNT(*)
FROM decisions
WHERE task_id = ? AND status = 'open'
`

func (q *Queries) CountOpenDecisionsForTask(ctx context.Context, taskID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenDecisionsForTask, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (
  id, goal_id, title, status, agent, files, sort_order, declare_key,
  claimed_by, claimed_at, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(goal_id, declare_key) DO NOTHING
`

type CreateTaskParams struct {
	ID         string
	GoalID     string
	Title      string
	Status     string
	Agent      string
	Files      string
	SortOrder  int64
	DeclareKey string
	ClaimedBy  string
	ClaimedAt  sql.NullString
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.GoalID,
		arg.Title,
		arg.Status,
		arg.Agent,
		arg.Files,
		arg.SortOrder,
		arg.DeclareKey,
		arg.ClaimedBy,
		arg.ClaimedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getTaskClaimedBy = `-- name: GetTaskClaimedBy :one
SELECT claimed_by
FROM tasks
WHERE id = ?
`

func (q *Queries) GetTaskClaimedBy(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskClaimedBy, id)
	var claimed_by string
	err := row.Scan(&claimed_by)
	return claimed_by, err
}

const getTaskForClaim = `-- name: GetTaskForClaim :one
SELECT goal_id, title, status, claimed_by, files
FROM tasks
WHERE id = ?
`

type GetTaskForClaimRow struct {
	GoalID    string
	Title     string
	Status    string
	ClaimedBy string
	Files     string
}

func (q *Queries) GetTaskForClaim(ctx context.Context, id string) (GetTaskForClaimRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskForClaim, id)
	var i GetTaskForClaimRow
	err := row.Scan(
		&i.GoalID,
		&i.Title,
		&i.Status,
		&i.ClaimedBy,
		&i.Files,
	)
	return i, err
}

const getTaskGoalID = `-- name: GetTaskGoalID :one
SELECT goal_id
FROM tasks
WHERE id = ?
`

func (q *Queries) GetTaskGoalID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskGoalID, id)
	var goal_id string
	err := row.Scan(&goal_id)
	return goal_id, err
}

const listClaimedTasksForConflict = `-- name: ListClaimedTasksForConflict :many
SELECT id, title, status, claimed_by, files
FROM tasks
WHERE id <> ?
  AND claimed_by <> ''
  AND claimed_by <> ?
  AND status NOT IN (?, ?)
ORDER BY sort_order, id
`

type ListClaimedTasksForConflictParams struct {
	ID        string
	ClaimedBy string
	Status    string
	Status_2  string
}

type ListClaimedTasksForConflictRow struct {
	ID        string
	Title     string
	Status    string
	ClaimedBy string
	Files     string
}

func (q *Queries) ListClaimedTasksForConflict(ctx context.Context, arg ListClaimedTasksForConflictParams) ([]ListClaimedTasksForConflictRow, error) {
	rows, err := q.db.QueryContext(ctx, listClaimedTasksForConflict,
		arg.ID,
		arg.ClaimedBy,
		arg.Status,
		arg.Status_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClaimedTasksForConflictRow
	for rows.Next() {
		var i ListClaimedTasksForConflictRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.ClaimedBy,
			&i.Files,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAlternatives = `-- name: ListTaskAlternatives :many
SELECT id, title, status, claimed_by, files
FROM tasks
WHERE goal_id = ?
  AND id <> ?
ORDER BY sort_order, id
`

type ListTaskAlternativesParams struct {
	GoalID string
	ID     string
}

type ListTaskAlternativesRow struct {
	ID        string
	Title     string
	Status    string
	ClaimedBy string
	Files     string
}

func (q *Queries) ListTaskAlternatives(ctx context.Context, arg ListTaskAlternativesParams) ([]ListTaskAlternativesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAlternatives, arg.GoalID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskAlternativesRow
	for rows.Next() {
		var i ListTaskAlternativesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.ClaimedBy,
			&i.Files,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT
  id, goal_id, title, status, agent, files, sort_order, declare_key,
  claimed_by, claimed_at, created_at, updated_at
FROM tasks
WHERE goal_id = ?
ORDER BY sort_order
`

func (q *Queries) ListTasks(ctx context.Context, goalID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Title,
			&i.Status,
			&i.Agent,
			&i.Files,
			&i.SortOrder,
			&i.DeclareKey,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTask = `-- name: ReleaseTask :execresult
UPDATE tasks
SET claimed_by = '', claimed_at = NULL, updated_at = ?
WHERE id = ?
`

type ReleaseTaskParams struct {
	UpdatedAt string
	ID        string
}

func (q *Queries) ReleaseTask(ctx context.Context, arg ReleaseTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, releaseTask, arg.UpdatedAt, arg.ID)
}

const taskExists = `-- name: TaskExists :one
SELECT id
FROM tasks
WHERE id = ?
`

func (q *Queries) TaskExists(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, taskExists, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :execresult
UPDATE tasks
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.UpdatedAt, arg.ID)
}

const updateTaskStatusAndReleaseClaim = `-- name: UpdateTaskStatusAndReleaseClaim :execresult
UPDATE tasks
SET status = ?, claimed_by = '', claimed_at = NULL, updated_at = ?
WHERE id = ?
`

type UpdateTaskStatusAndReleaseClaimParams struct {
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateTaskStatusAndReleaseClaim(ctx context.Context, arg UpdateTaskStatusAndReleaseClaimParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTaskStatusAndReleaseClaim, arg.Status, arg.UpdatedAt, arg.ID)
}
