// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ui_settings.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getUILocale = `-- name: GetUILocale :one
SELECT locale
FROM ui_settings
WHERE id = 1
`

func (q *Queries) GetUILocale(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getUILocale)
	var locale string
	err := row.Scan(&locale)
	return locale, err
}

const setUILocale = `-- name: SetUILocale :execresult
UPDATE ui_settings
SET locale = ?
WHERE id = 1
`

func (q *Queries) SetUILocale(ctx context.Context, locale string) (sql.Result, error) {
	return q.db.ExecContext(ctx, setUILocale, locale)
}
